# Generated by Django 5.1.2 on 2025-01-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('groups', '0002_groupmember_organization_alter_groupmember_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grouped_organization', to='accounts.organization'),
        ),
    ]
