# Generated by Django 5.1.2 on 2025-01-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupevent_groupeventbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='location',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('Organization', 'Organization'), ('Salesforce', 'Salesforce'), ('Microsoft Teams', 'Microsoft Teams'), ('Skype', 'Skype'), ('Webex', 'Webex'), ('Slack', 'Slack')], max_length=255),
        ),
    ]
