# Generated by Django 5.1.2 on 2025-01-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groupeventreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='recurrence_days',
            field=models.CharField(blank=True, help_text="Comma-separated days for weekly recurrence, e.g., 'Monday, Wednesday'.", max_length=50),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20, null=True),
        ),
    ]
