# Generated by Django 5.1.2 on 2025-01-12 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('groups', '0008_groupevent_recurrence_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ADD_MEMBER', 'Added member'), ('REMOVE_MEMBER', 'Removed member'), ('CREATE_TASK', 'Created task'), ('UPDATE_TASK', 'Updated task'), ('DELETE_TASK', 'Deleted task'), ('GROUP_CREATED', 'Created group'), ('GROUP_UPDATED', 'Updated group'), ('GROUP_DELETED', 'Deleted group'), ('INVITE_MEMBER', 'Invited member')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
