# Generated by Django 5.1.2 on 2025-01-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_groupactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupactivity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupevent'),
        ),
        migrations.AlterField(
            model_name='groupactivity',
            name='action_type',
            field=models.CharField(choices=[('ADD_MEMBER', 'Added member'), ('REMOVE_MEMBER', 'Removed member'), ('CREATE_TASK', 'Created task'), ('UPDATE_TASK', 'Updated task'), ('DELETE_TASK', 'Deleted task'), ('GROUP_CREATED', 'Created group'), ('GROUP_UPDATED', 'Updated group'), ('GROUP_DELETED', 'Deleted group'), ('INVITE_MEMBER', 'Invited member'), ('INVITATION_ACCEPT', 'Invitation accepted'), ('INVITATION_REJECT', 'Invitation rejected'), ('MEMBER_DISCARD', 'Member removed'), ('CREATE_EVENT', 'Event created'), ('BOOK_EVENT', 'Event booked'), ('MARK_ABSENT', 'Marked as absent'), ('SET_EVENT_REMINDER', 'Reminder set'), ('DELETE_EVENT', 'Event deleted'), ('RECURRING_EVENT', 'Set event as recurring')], max_length=50),
        ),
    ]
