# Generated by Django 5.1.2 on 2024-11-21 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_roles', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(choices=[('techsnap', 'Techsnap'), ('datasnap', 'Datasnap'), ('moviesnap', 'Moviesnap')], max_length=100, unique=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_admin', to='new_roles.profile')),
                ('employees', models.ManyToManyField(blank=True, related_name='organization_employees', to='new_roles.profile')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_manager', to='new_roles.profile')),
            ],
        ),
    ]
