# Generated by Django 5.1.2 on 2025-01-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0011_alter_activitylog_action_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('COMMENT', 'Commented on the task'), ('NOTE', 'Added a note'), ('START_TIMER', 'Started the timer'), ('STOP_TIMER', 'Stopped the timer'), ('PROGRESS_UPDATE', 'Updated progress'), ('TASK_CREATED', 'Created a task'), ('TASK_COMPLETED', 'Marked task as completed'), ('TASK_PENDING', 'Marked task as pending'), ('TAG_ADDED', 'Added a tag in task'), ('TAG_REMOVED', 'Removed the tag from task'), ('TIME_SPENT', 'Spent time on task'), ('RAISED_PROBLEM', 'Raised a problem'), ('RESOLVED_PROBLEM', 'Resolved a problem'), ('NOTE_ELIMINATED', 'Eliminated a note'), ('NOTE_AMENDED', 'Amended a note'), ('COMMENT_MODIFIED', 'The comment was modified by.')], max_length=50),
        ),
    ]
