# Generated by Django 5.1.6 on 2025-03-08 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('group_tasks', '0013_alter_activitylog_action'),
        ('groups', '0010_groupactivity_event_alter_groupactivity_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short and descriptive title for the subtask.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the subtask.', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='The priority level of the subtask.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', help_text='The current status of the subtask.', max_length=20)),
                ('deadline', models.DateTimeField(help_text='The deadline for completing the subtask.')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100) of subtask completion.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this subtask.', on_delete=django.db.models.deletion.CASCADE, related_name='created_subtasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The group this subtask belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='groups.group')),
                ('organization', models.ForeignKey(help_text='The organization under which this subtask is created.', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='accounts.organization')),
                ('task', models.ForeignKey(help_text='The parent task this subtask belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='group_tasks.task')),
            ],
        ),
    ]
