# Generated by Django 5.1.6 on 2025-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0016_recentvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queries_sent',
            field=models.IntegerField(default=0),
        ),
    ]
