# Generated by Django 5.1.6 on 2025-03-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('group_tasks', '0017_task_queries_sent'),
        ('groups', '0010_groupactivity_event_alter_groupactivity_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTaskQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(choices=[('task_query', 'Task Queries'), ('facing_bug', 'Facing Bugs'), ('urgent_issue', 'Urgent Issue'), ('need_clarification', 'Need Clarification'), ('other', 'Other')], default='task_query', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_scheduled', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tasks.task')),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
