# Generated by Django 5.1.6 on 2025-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0018_meetingtaskquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtaskquery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
