# Generated by Django 5.1.6 on 2025-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0019_meetingtaskquery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtaskquery',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
