# Generated by Django 5.1.6 on 2025-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0020_meetingtaskquery_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtaskquery',
            name='meeting_link',
            field=models.URLField(blank=True, default='https://meet.google.com/new', null=True),
        ),
    ]
