# Generated by Django 5.1.6 on 2025-03-10 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('group_tasks', '0021_alter_meetingtaskquery_meeting_link'),
        ('groups', '0010_groupactivity_event_alter_groupactivity_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Message content related to the task.', null=True)),
                ('files', models.FileField(blank=True, help_text='Optional file attachment for the communication.', null=True, upload_to='task_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was sent.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the message was last updated.')),
                ('group', models.ForeignKey(help_text='The group associated with this task communication.', on_delete=django.db.models.deletion.CASCADE, related_name='task_group_communications', to='groups.group')),
                ('organization', models.ForeignKey(help_text='The organization associated with this task communication.', on_delete=django.db.models.deletion.CASCADE, related_name='task_communications', to='accounts.organization')),
                ('sender', models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_task_messages', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='The task for which this communication is happening.', on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='group_tasks.task')),
            ],
            options={
                'verbose_name': 'Task Communication',
                'verbose_name_plural': 'Task Communications',
                'ordering': ['-created_at'],
            },
        ),
    ]
