# Generated by Django 5.1.6 on 2025-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0022_communicatetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='remind_before_due_date',
            field=models.CharField(blank=True, choices=[('one_day_before', 'One day before'), ('before_a_week', 'Before a week'), ('before_a_month', 'Before a month'), ('never', 'Never'), ('just_send_me_the_reminder_every_morning_till_task_completes', 'Just send me the reminder every morning till task completes')], default='never', max_length=300, null=True),
        ),
    ]
