# Generated by Django 5.1.6 on 2025-03-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0023_subtask_remind_before_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='behaviour',
            field=models.CharField(blank=True, choices=[('prevent_completion_before_main_task', 'Prevent completion before main task'), ('autocomplete_if_main_task_completes', 'Auto complete if main task completes'), ('shouldn_affect_main_task', 'Shouldnt affect main task'), ('repeat_for_5_times_after_completion', 'Repeat for 5 times after completion')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='can_edit_task',
            field=models.BooleanField(blank=True, default=False, help_text='if yes task accomplisher can edit the subtask', null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='delete_after_completion',
            field=models.BooleanField(blank=True, default=False, help_text='if yes the task will be wiped after completion', null=True),
        ),
    ]
