# Generated by Django 5.1.6 on 2025-03-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('group_tasks', '0024_subtask_behaviour_subtask_can_edit_task_and_more'),
        ('groups', '0010_groupactivity_event_alter_groupactivity_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('remind_x_minutes_before', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_x_hours_before', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_x_days_before', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_x_weeks_before', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_x_months_before', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_assignee_every_morning', models.BooleanField(default=False)),
                ('remind_assignee_every_evening', models.BooleanField(default=False)),
                ('remind_every_x_days', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_every_x_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_every_x_months', models.PositiveIntegerField(blank=True, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App Notification'), ('push', 'Push Notification'), ('webhook', 'Webhook (API)')], default='in_app', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('auto_reschedule', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_reminders', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to='accounts.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='group_tasks.task')),
            ],
            options={
                'ordering': ['reminder_time'],
            },
        ),
    ]
