# Generated by Django 5.1.6 on 2025-03-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0025_taskreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('pending_approvel', 'Pending approval'), ('need_changes', 'Need changes')], default='pending', help_text='The current status of the task.', max_length=20),
        ),
    ]
