# Generated by Django 5.1.6 on 2025-03-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('group_tasks', '0026_alter_task_status'),
        ('groups', '0010_groupactivity_event_alter_groupactivity_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('pending_approval', 'Pending approval'), ('need_changes', 'Need changes')], default='pending', help_text='The current status of the task.', max_length=20),
        ),
        migrations.CreateModel(
            name='CalPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Number of CalPoints awarded for this task.')),
                ('reason', models.TextField(blank=True, help_text='Reason why the user earned these CalPoints.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the points were awarded.')),
                ('group', models.ForeignKey(blank=True, help_text='Group associated with the task, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calpoints', to='groups.group')),
                ('organization', models.ForeignKey(help_text='Organization where the task was completed.', on_delete=django.db.models.deletion.CASCADE, related_name='calpoints', to='accounts.organization')),
                ('task', models.ForeignKey(help_text='Task for which the CalPoints were awarded.', on_delete=django.db.models.deletion.CASCADE, related_name='calpoints', to='group_tasks.task')),
                ('user', models.ForeignKey(help_text='User who earned the CalPoints.', on_delete=django.db.models.deletion.CASCADE, related_name='calpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CalPoints Record',
                'verbose_name_plural': 'CalPoints Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
