# Generated by Django 5.1.6 on 2025-03-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0028_pendingrewardnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrewardnotification',
            name='calpoints',
        ),
    ]
