# Generated by Django 5.1.6 on 2025-03-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0030_automationtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtask',
            name='automations',
        ),
        migrations.RemoveField(
            model_name='automationtask',
            name='user',
        ),
        migrations.AddField(
            model_name='automationtask',
            name='assign_task_if_previous_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='auto_assign_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='escalate_if_not_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='generate_summary_after_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='log_activity_on_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='notify_task_creator_on_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='progress_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='remind_before_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='send_greeting_after_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='send_submission_request_after_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='send_welcome_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='translate_in_english',
            field=models.BooleanField(default=False),
        ),
    ]
