# Generated by Django 5.1.6 on 2025-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0032_automationtask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
