# Generated by Django 5.1.6 on 2025-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0033_automationtask_last_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='processed_tasks',
            field=models.ManyToManyField(blank=True, related_name='processed_automations', to='group_tasks.task'),
        ),
    ]
