# Generated by Django 5.1.6 on 2025-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0034_automationtask_processed_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='processed_submission_tasks',
            field=models.ManyToManyField(blank=True, related_name='processed_submission_automations', to='group_tasks.task'),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='processed_welcome_tasks',
            field=models.ManyToManyField(blank=True, related_name='processed_welcome_automations', to='group_tasks.task'),
        ),
    ]
