# Generated by Django 5.1.6 on 2025-03-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0035_automationtask_processed_submission_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_request_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='welcome_text_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
