# Generated by Django 5.1.6 on 2025-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0036_task_submission_request_sent_task_welcome_text_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_update_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
