# Generated by Django 5.1.6 on 2025-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0037_task_progress_update_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='after_approval_greeting_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
