# Generated by Django 5.1.6 on 2025-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0039_task_after_completion_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='escalate_if_not_completed_action',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
