# Generated by Django 5.1.6 on 2025-03-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0040_task_escalate_if_not_completed_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calpoints',
            name='group',
        ),
        migrations.RemoveField(
            model_name='calpoints',
            name='task',
        ),
    ]
