# Generated by Django 5.1.6 on 2025-03-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0041_remove_calpoints_group_remove_calpoints_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_before_deadline_notification_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
