# Generated by Django 5.1.6 on 2025-03-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0042_task_remind_before_deadline_notification_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='remind_before_deadline_notification_sent',
            new_name='reminder_before_1_day_sent',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_before_2_days_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
