# Generated by Django 5.1.6 on 2025-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0043_rename_remind_before_deadline_notification_sent_task_reminder_before_1_day_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_assign_reviewer_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
