# Generated by Django 5.1.6 on 2025-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0045_taskcompletionactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log_completion_activity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
