# Generated by Django 5.1.6 on 2025-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0047_automationtask_install_new_apps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='install_new_app_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
