# Generated by Django 5.1.6 on 2025-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0048_task_install_new_app_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='extend_deadline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_extend_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
