# Generated by Django 5.1.6 on 2025-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0049_automationtask_extend_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='automate_stalled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='automate_stalled_action',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
