# Generated by Django 5.1.6 on 2025-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0050_automationtask_automate_stalled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='task_priortization',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_priortization_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
