# Generated by Django 5.1.6 on 2025-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0051_automationtask_task_priortization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='auto_schedule_meeting_on_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_meeting_scheduled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
