# Generated by Django 5.1.6 on 2025-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0052_automationtask_auto_schedule_meeting_on_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='overdue_notification',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_notification_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
