# Generated by Django 5.1.6 on 2025-03-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0053_automationtask_overdue_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='ai_subtasks',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_created_subtasks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
