# Generated by Django 5.1.6 on 2025-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0054_automationtask_ai_subtasks_task_ai_created_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='cal_ai_plans',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cal_ai_plans_executed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
