# Generated by Django 5.1.6 on 2025-03-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0055_automationtask_cal_ai_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_completion_time',
            field=models.DurationField(blank=True, help_text='Estimated time required to complete the task', null=True),
        ),
    ]
