# Generated by Django 5.1.6 on 2025-03-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0056_task_estimated_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='send_meeting_summary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting_summary_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
