# Generated by Django 5.1.6 on 2025-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0057_automationtask_send_meeting_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='remind_my_meetings',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting_reminder_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
