# Generated by Django 5.1.6 on 2025-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0058_automationtask_remind_my_meetings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='provide_chat_insights',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='chat_insights_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
