# Generated by Django 5.1.6 on 2025-03-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0059_automationtask_provide_chat_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicatetask',
            name='flagged_for_review',
            field=models.BooleanField(blank=True, default=False, help_text='Flagged for manager review if negative sentiment is detected.', null=True),
        ),
        migrations.AddField(
            model_name='communicatetask',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', help_text='Sentiment of the message (Positive, Neutral, Negative).', max_length=10, null=True),
        ),
    ]
