# Generated by Django 5.1.6 on 2025-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0060_communicatetask_flagged_for_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='send_daily_activities',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='activity_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
