# Generated by Django 5.1.6 on 2025-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0061_automationtask_send_daily_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='send_daily_activities',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
