# Generated by Django 5.1.6 on 2025-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0062_alter_automationtask_send_daily_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='share_problems_to_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='problem_sent_to_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
