# Generated by Django 5.1.6 on 2025-03-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0063_automationtask_share_problems_to_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='remin_me_every_morning',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
