# Generated by Django 5.1.6 on 2025-03-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0064_automationtask_remin_me_every_morning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationtask',
            old_name='remin_me_every_morning',
            new_name='remind_me_every_morning',
        ),
    ]
