# Generated by Django 5.1.6 on 2025-03-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0067_taskbackup_task_alter_taskbackup_backup_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbackup',
            name='activity_logs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='automations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='conversation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='meetings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='reminders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='subtasks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='time_traced',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
