# Generated by Django 5.1.6 on 2025-03-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0068_taskbackup_activity_logs_taskbackup_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbackup',
            name='problem',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
