# Generated by Django 5.1.6 on 2025-03-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0069_taskbackup_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskbackup',
            old_name='file_size',
            new_name='backup_size',
        ),
    ]
