# Generated by Django 5.1.6 on 2025-03-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0072_activitybackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybackup',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tasks.taskbackup'),
        ),
    ]
