# Generated by Django 5.1.6 on 2025-03-27 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0074_remove_activitybackup_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybackup',
            name='action',
            field=models.CharField(choices=[('created', 'Backup Created'), ('restored', 'Backup Restored'), ('download', 'Backup Downloaded'), ('deleted', 'Backup Deleted'), ('scheduled', 'Backup Scheduled')], max_length=10),
        ),
        migrations.CreateModel(
            name='TaskProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_change', models.IntegerField()),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='group_tasks.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
