# Generated by Django 5.1.6 on 2025-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0075_alter_activitybackup_action_taskprogresslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
