# Generated by Django 5.1.6 on 2025-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0078_issueroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueroom',
            name='files',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='issue_files/'),
        ),
    ]
