"""
Django settings for ch project.
Generated by 'django-admin startproject' using Django 5.1.1.
For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""






from pathlib import Path
import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent




STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


STATICFILES_DIRS = [
    BASE_DIR / 'static',  
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



SECRET_KEY = 'django-insecure-2_5v35*4-ylcnkadmjcbghfoa3^fhq8%kun$ywajnp7jd3_s2j'


DEBUG = True

ALLOWED_HOSTS = []

import os 

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# Application definition

INSTALLED_APPS = [
    'outh',
    'direct_message',
    'profiles',
    'organizations',
    'meet',
    'calendar_plus',
    'daphne',
    'ai',
    'channels',
    'chat',
    'accounts',
    'notify',
    'new_roles',
    'rest_framework',
    'corsheaders',
     'tinymce',
     'contacts',
     'security',
     'groups',
     'group_tasks',
    'widget_tweaks',
    'solo_communication',
    'ckeditor_uploader',
    'organization_channels',
     'formtools',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'rest_framework.authtoken',  
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'meet.middlewares.AdminOnlyMiddleware',

]

ROOT_URLCONF = 'ch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'ch.asgi.application'

# WSGI_APPLICATION = 'ch.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', 
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'NAME': 'calendar_pro', 
        'USER': 'postgres',  
        'PASSWORD': 'skl12qw@#',  
    }
}

# RENDER EXTERNAL DATABASE URL 


DATABASES["default"] = dj_database_url.parse("postgresql://calendar_p_lus_database_user:bPydl91jveJL1UvAyqC1tKpXBXJDl2BU@dpg-cujobeogph6c73bjh4h0-a.oregon-postgres.render.com/calendar_p_lus_database")

# postgresql://calendar_p_lus_database_user:bPydl91jveJL1UvAyqC1tKpXBXJDl2BU@dpg-cujobeogph6c73bjh4h0-a.oregon-postgres.render.com/calendar_p_lus_database












CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

STATIC_URL = '/static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'ch/static'), 
]


# rest framework configuration

REST_FRAMEWORK={
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':2,
    'DEFAULT_THROTTLE_CLASSES':[
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES':{
        'anon':'1/day',
        'user':'100/min'
    },
}

# EMAIL BACKEND SERVICES

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587 
EMAIL_HOST_USER = 'vishaldudhabarve105@gmail.com'
EMAIL_HOST_PASSWORD = 'esmv cymg qdns jqqz' 
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'vishaldudhabarve105@gmail.com'




# set redis as the message broker 
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  

CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_RESULT_EXTENDED = True

# Celery Beat settings for periodic tasks
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# json as the task serializer
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']


import logging

logging.basicConfig(level=logging.DEBUG)



CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_ALL_ORIGINS = True



# credentials.json

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

SESSION_COOKIE_AGE = 1209600  
import os
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Correct MEDIA settings
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media") 

SITE_URL = ' http://127.0.0.1:8000/calendar'






STATIC_URL = '/static/'


STATICFILES_DIRS = [
    BASE_DIR ,"static",
]



STATIC_URL = '/static/'  

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), ]

# If using collectstatic for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  


# GOOGLE CALENDAR  CREDENTIALS


GOOGLE_CLIENT_ID = "854433356192-d81dha5vahp50pj5f8g5c9fqesd7flti.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "http://localhost:8000/oauth/callback/"





