# Generated by Django 5.1.5 on 2025-01-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0005_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
