# Generated by Django 5.1.5 on 2025-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0011_alter_activitychannel_action_type_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week'), ('1_month', '1 Month'), ('permanent', 'Permanent')], default='permanent', max_length=10),
        ),
    ]
