# Generated by Django 5.1.5 on 2025-01-22 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('organization_channels', '0012_ban_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitychannel',
            name='action_type',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('MENTION', 'Mention'), ('EMOJI', 'Emoji'), ('LINK', 'Link'), ('FILE_UPLOAD', 'File Upload'), ('JOIN', 'Join'), ('LEAVE', 'Leave'), ('DATA_EXPORT', 'Data export'), ('EXPLORE_STATISTICS', 'Explore statistics'), ('MESSAGES_DELETE', 'Messages delete'), ('MESSAGE_DELETE', 'Message_delete'), ('LINK_DELETE', 'Link delete'), ('MESSAGE_EDITED', 'Message edited'), ('LINK_EDITED', 'Link edited'), ('FILTERED_MESSAGES', 'Filtered messages'), ('BAN_USER', 'Ban user')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChannelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='organization_channels.channel')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('granted_to_organization', models.ForeignKey(help_text='The organization being granted access to the channel.', on_delete=django.db.models.deletion.CASCADE, related_name='granted_channel_accesses', to='accounts.organization')),
                ('owning_organization', models.ForeignKey(help_text='The organization that owns the channel.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_channel_accesses', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Channel Access',
                'verbose_name_plural': 'Channel Accesses',
                'unique_together': {('channel', 'granted_to_organization')},
            },
        ),
    ]
