# Generated by Django 5.1.5 on 2025-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0013_alter_activitychannel_action_type_channelaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitychannel',
            name='action_type',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('MENTION', 'Mention'), ('EMOJI', 'Emoji'), ('LINK', 'Link'), ('FILE_UPLOAD', 'File Upload'), ('JOIN', 'Join'), ('LEAVE', 'Leave'), ('DATA_EXPORT', 'Data export'), ('EXPLORE_STATISTICS', 'Explore statistics'), ('MESSAGES_DELETE', 'Messages delete'), ('MESSAGE_DELETE', 'Message_delete'), ('LINK_DELETE', 'Link delete'), ('MESSAGE_EDITED', 'Message edited'), ('LINK_EDITED', 'Link edited'), ('FILTERED_MESSAGES', 'Filtered messages'), ('BAN_USER', 'Ban user'), ('CHANNEL_ACCESS', 'Channel access')], max_length=20),
        ),
    ]
