# Generated by Django 5.1.5 on 2025-01-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('organization_channels', '0014_alter_activitychannel_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_period', models.IntegerField(choices=[(30, '30 Days'), (45, '45 Days'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year')], default=30, help_text='Retention period for auto-deleting messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='organization_channels.channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_retention_policies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'channel')},
            },
        ),
    ]
