# Generated by Django 5.1.5 on 2025-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0015_retentionpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionpolicy',
            name='custom_days',
            field=models.PositiveIntegerField(blank=True, help_text="Enter custom days if retention period is set to 'Custom'", null=True),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='retention_period',
            field=models.IntegerField(choices=[(30, '30 Days'), (45, '45 Days'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year'), (0, 'Custom')], default=30, help_text='Retention period for auto-deleting messages'),
        ),
    ]
