# Generated by Django 5.1.5 on 2025-01-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0018_abusedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
