# Generated by Django 5.1.5 on 2025-01-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('organization_channels', '0025_recurrencehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitychannel',
            name='action_type',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('MENTION', 'Mention'), ('EMOJI', 'Emoji'), ('LINK', 'Link'), ('FILE_UPLOAD', 'File Upload'), ('JOIN', 'Join'), ('LEAVE', 'Leave'), ('DATA_EXPORT', 'Data export'), ('EXPLORE_STATISTICS', 'Explore statistics'), ('MESSAGES_DELETE', 'Messages delete'), ('MESSAGE_DELETE', 'Message_delete'), ('LINK_DELETE', 'Link delete'), ('MESSAGE_EDITED', 'Message edited'), ('LINK_EDITED', 'Link edited'), ('FILTERED_MESSAGES', 'Filtered messages'), ('BAN_USER', 'Ban user'), ('CHANNEL_ACCESS', 'Channel access'), ('SET_RETENTION_POLICY', 'Set retention policy'), ('PINNED_MESSAGE', 'Pinned message'), ('STARRED_MESSAGE', 'Starred message'), ('MESSAGE_REPLY', 'Message reply'), ('SET_RECURRING_MESSAGE', 'Set recurring message'), ('PREVENT_RECURRING_MESSAGE', 'Prevent recurring message'), ('WARN_ABOUT_ABUSIVE_BEHAVIOUR', 'Warn about abusive behaviour')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitychannel',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organization_channels.channel'),
        ),
        migrations.AlterField(
            model_name='activitychannel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.organization'),
        ),
    ]
