# Generated by Django 5.1.5 on 2025-01-26 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('organization_channels', '0028_channelevents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_message_moderation', models.BooleanField(default=False)),
                ('allow_file_uploads', models.BooleanField(default=True)),
                ('allow_emoji_usage', models.BooleanField(default=True)),
                ('allow_mentions', models.BooleanField(default=True)),
                ('enable_event_creation', models.BooleanField(default=True)),
                ('enable_public_access', models.BooleanField(default=False)),
                ('allow_external_links', models.BooleanField(default=True)),
                ('allow_invites', models.BooleanField(default=True)),
                ('allow_remove_members', models.BooleanField(default=True)),
                ('can_edit_channel_name', models.BooleanField(default=True)),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('event_reminder_text', models.TextField(blank=True, null=True)),
                ('banned_keywords', models.TextField(blank=True, null=True)),
                ('channel_logo', models.ImageField(blank=True, null=True, upload_to='channel_logos/')),
                ('message_timeout', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization_channels.channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings', to='accounts.organization')),
            ],
        ),
    ]
