# Generated by Django 5.1.5 on 2025-01-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0029_channelsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsettings',
            name='allow_emoji_usage',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='allow_external_links',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='allow_file_uploads',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='allow_invites',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='allow_mentions',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='allow_remove_members',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='can_edit_channel_name',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='enable_event_creation',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='enable_message_moderation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='enable_notifications',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='enable_public_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='channelsettings',
            name='message_timeout',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
    ]
