# Generated by Django 5.1.5 on 2025-01-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0032_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
    ]
