# Generated by Django 5.1.5 on 2025-01-28 18:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0035_alertnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotification',
            name='message',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
