# Generated by Django 5.1.5 on 2025-01-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0036_alter_alertnotification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='schedule_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('after_days', 'After X Days'), ('custom_date', 'Custom Date')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
