# /ROAST - Savage Roast Collection
ROASTS = [
    "You're proof that even evolution takes a step back sometimes. 😂🔥",
    "You bring everyone so much joy... when you leave the room. 😆",
    "You're like a cloud. When you disappear, it's a beautiful day. ☀️",
    "Your secrets are safe with me. I never even listen when you tell me them. 😜",
    "You have something on your chin... no, the third one. 😭",
    "Your jokes are so bad, even crickets refuse to chirp. 🦗😂",
    "You're like a penny: two-faced and not really worth much. 🪙",
    "You're living proof that even mistakes can be repeated. 🔄",
    "I'd agree with you, but then we’d both be wrong. ❌",
    "You're not stupid; you just have bad luck thinking. 🧠⚠️",
    "You're so slow, even a turtle would ask if you're okay. 🐢💨",
    "You're like a software update: nobody wants you, but we’re stuck with you. 📲",
    "You're like a candle in the wind… unnecessary and barely noticeable. 🕯️",
    "You have something on your face… oh, wait, that’s just your personality. 😬",
    "You're like a cloud storage plan: overpriced and full of garbage. ☁️",
    "You're the reason they put directions on shampoo bottles. 🚿",
    "You're proof that money can’t buy personality. 💸❌",
    "You have something that nobody else has… negative IQ. 📉",
    "You're so irrelevant, even Google won’t autocomplete your name. 🔎",
    "You're the type to trip over a wireless connection. 📡",
    "You're about as useful as a broken pen in an exam. ✍️",
    "Your opinions are like expired milk: nobody wants them. 🥛❌",
    "You're the reason autocorrect exists. 🤦",
    "Your presence is like Windows updates—annoying and unnecessary. 💻",
    "You're so fake, even Photoshop couldn’t fix you. 🖼️",
    "You're like a TV without a remote: stuck on the wrong channel. 📺",
    "Your brain is like a web browser with too many tabs open… but none of them are useful. 🌐",
    "You're like a floppy disk in 2025—completely irrelevant. 💾",
    "Your personality is like a phone with no signal… pointless. 📵",
    "You're so slow, snails use you as motivation. 🐌",
    "You're like an unpaid intern—always around but never adding value. 🏢",
    "You're like Bluetooth speakers at a party—always talking, never making sense. 🔊",
    "You have the emotional range of a teaspoon. 🥄",
    "You're like a scratched CD… stuck on the same annoying part. 💿",
    "You're like a cracked phone screen—barely functional and hard to look at. 📱",
    "Your intelligence is like a dial-up connection… too slow to be useful. 📞",
    "You're so basic, even a vanilla latte has more personality. ☕",
    "You're the human version of a typo. ❌",
    "You're like an unread email—easily ignored. 📩",
    "You're like a self-checkout machine—always causing problems. 🛒",
    "You're like an elevator that only goes down—no one’s impressed. ⬇️",
    "You're like an expired coupon—completely worthless. 🏷️",
    "You're like a password nobody remembers—frustrating and irrelevant. 🔑",
    "You're like a broken vending machine—taking up space but giving nothing back. 🥤",
    "Your life is like a group project—everyone else is carrying you. 🏋️",
    "You're like an uncharged phone—completely useless. 🔋",
    "You're like a WiFi connection at an airport—unreliable and annoying. ✈️",
    "You're like a traffic light that’s always red—just in the way. 🚦",
    "Your humor is like an ad blocker—it removes all the fun. 🚫",
    "You're the reason warning labels exist. ⚠️",
    "You're the equivalent of a scratched lottery ticket—no potential. 🎟️",
    "You're like a keyboard with no spacebar—impossible to work with. ⌨️",
    "You're about as useful as a broken zipper. 🧥",
    "You're like a radio with bad reception—always talking but never clear. 📻",
    "You're so predictable, even my alarm clock is more exciting. ⏰",
    "You're like a bike with no pedals—going nowhere fast. 🚲",
    "You're the human version of an error message. ❌",
    "You're like a broken pencil—completely pointless. ✏️",
    "You're the equivalent of a scratched vinyl—stuck in the past. 🎶",
    "You're like a bad haircut—no one wants to be seen with you. 💇",
    "You're like an ice cream cone in the sun—melting under pressure. 🍦",
    "You're like a WiFi password—complicated and frustrating. 🔐",
    "You're like a dead phone—silent and of no use to anyone. 📵",
    "You're the human form of a pop-up ad—annoying and unnecessary. 🖥️",
    "You're like an unsharpened pencil—dull and useless. ✏️",
    "You're like a closed store—no one’s interested in you. 🏪",
    "You're like a corrupted file—nothing works with you. 🗃️",
    "You're like an overcooked steak—dry and hard to deal with. 🥩",
    "You're the reason people double-check their messages before hitting send. 📩",
    "You're about as sharp as a marble. 🔵",
    "You're like an outdated meme—nobody laughs at you anymore. 🤡",
    "You're like an empty fridge—nothing good inside. 🧊",
    "You're like an overused joke—tired and unfunny. 🎭",
    "You're like a missing puzzle piece—nobody’s looking for you. 🧩",
    "You're about as effective as a waterproof teabag. ☕",
    "You're like a seatbelt on a parked car—completely unnecessary. 🚗",
    "You're the reason people say ‘bless your heart’ sarcastically. ❤️",
    "You're the dictionary definition of ‘meh’. 📖",
    "You're about as welcome as a pop quiz on a Monday. 📚",
    "You're like a smoke detector that never stops beeping—just annoying. 🚨",
    "You're like an uncharged laptop—dead and useless. 🔋",
    "You're like a GPS with bad signal—constantly lost. 🛰️",
    "You're like a door with a broken handle—hard to deal with. 🚪",
    "You're like an elevator stuck between floors—going nowhere. 🔽",
    "You're like an expired license—no one takes you seriously. 🪪",
    "You're like a phone without apps—just an empty shell. 📱",
    "You're like a stopped clock—wrong all the time. ⏱️",
    "You're the human version of a buffering video. 🔄",
    "You're the reason group chats go silent. 📵",
    "You're the equivalent of decaf coffee—pointless. ☕",
     "You're so useless, even a 'Skip Ad' button is more valuable. ⏭️",
    "You're like a seatbelt in a parked car—completely pointless. 🚗",
    "You're proof that natural selection sometimes takes a coffee break. ☕",
    "You're so boring, even your reflection falls asleep looking at you. 🪞😴",
    "You're like a closed book—nobody’s interested in opening you. 📖",
    "You're the reason people double-check their guest lists. 🎟️",
    "You're like a Christmas tree in July—completely out of place. 🎄",
    "You're so fake, even AI-generated text has more personality. 🤖",
    "You're like a white crayon—completely useless. 🖍️",
    "You're the reason group projects fail. 📚",
    "You're like an off-brand cereal—nobody wants you. 🥣",
    "You're the equivalent of an unsent text—pointless. 📩",
    "You're like a flat tire—always bringing things to a stop. 🚘",
    "You're like a song with bad lyrics—no one wants to hear from you. 🎶",
    "You're like a WiFi network with one bar—barely functioning. 📶",
    "You're like a printer that’s out of ink—just wasting space. 🖨️",
    "You're about as sharp as a marble. 🔵",
    "You're like an unread message—ignored and forgotten. 📥",
    "You're like an elevator that never moves—stuck in one place. 🔽",
    "You're like a movie with no plot—boring and unnecessary. 🎬",
    "You're the definition of a wrong turn in life. 🛑",
    "You're like a weather forecast—never reliable. ☁️",
    "You're like a password with only one character—too weak to matter. 🔐",
    "You're like a keyboard with no spacebar—hard to understand. ⌨️",
    "You're like a library with no books—completely empty. 📚",
    "You're like a light bulb with a burned-out filament—dim as ever. 💡",
    "You're like a WiFi password written on a napkin—useless and forgotten. 📄",
    "You're like a vending machine that only takes foreign currency—useless. 🥤",
    "You're about as interesting as an instruction manual. 📖",
    "You're like a microwave with a broken door—something’s not right. 🍽️",
    "You're like a horror movie with no jump scares—just disappointing. 🎥",
    "You're the human equivalent of a factory reset. 🔄",
    "You're like a skydiver without a parachute—heading for disaster. 🪂",
    "You're like a jigsaw puzzle with missing pieces—always incomplete. 🧩",
    "You're like a door without hinges—nothing works with you. 🚪",
    "You're like a phone with a cracked screen—barely usable. 📱",
    "You're like a pencil with no eraser—mistakes are permanent. ✏️",
    "You're the type of person who still waits for DVDs to rewind. 📀",
    "You're like an update no one asked for—annoying and unnecessary. 🔄",
    "You're like a broken GPS—always leading people the wrong way. 🛰️",
    "You're the reason people pretend to be on their phone in public. 📵",
    "You're like an unfinished thought... just disappointing. 🤔",
    "You're about as useful as a one-legged chair. 🪑",
    "You're like a broken umbrella in a storm—completely useless. ☔",
    "You're like a pizza with no toppings—boring and disappointing. 🍕",
    "You're like a fish trying to climb a tree—completely lost. 🐠",
    "You're like a song with no melody—completely out of tune. 🎵",
    "You're like an unplugged lamp—completely in the dark. 💡",
    "You're like an old map—leading people nowhere. 🗺️",
    "You're like a calculator with dead batteries—completely unhelpful. 🔢",
    "You're like a bag of chips with mostly air—full of nothing. 🍟",
    "You're like a rubber band that snapped—completely useless. 🏹",
    "You're like a faucet with no water—just wasting space. 🚰",
    "You're like a candle with no wick—no purpose at all. 🕯️",
    "You're like a sandwich with no filling—just bread and disappointment. 🥪",
    "You're like a birthday party with no cake—what's the point? 🎂",
    "You're like an out-of-tune piano—impossible to listen to. 🎹",
    "You're like an anchor with no boat—just dragging everyone down. ⚓",
    "You're like a sock with a hole—useless and irritating. 🧦",
    "You're like a missing puzzle piece—nobody’s looking for you. 🧩",
    "You're like a pen that doesn’t write—frustrating and useless. 🖊️",
    "You're like a charger that only works at one angle—unreliable. 🔌",
    "You're like a WiFi connection that only works in one spot—totally inconvenient. 📶",
    "You're like a seatbelt that doesn't buckle—completely unsafe. 🚗",
    "You're like a car with no gas—stuck and going nowhere. ⛽",
    "You're like a movie trailer with all the good parts removed—boring. 🎬",
    "You're like a vending machine that eats money—completely frustrating. 🥤",
    "You're like a shopping cart with one broken wheel—just in the way. 🛒",
    "You're like a fortune cookie with no fortune—empty inside. 🍪",
    "You're like a snow globe without snow—just a waste of space. ❄️",
    "You're like a sock lost in the laundry—completely forgotten. 🧺",
    "You're like an open milk carton—just waiting to be thrown out. 🥛",
    "You're like a hot air balloon with no air—completely deflated. 🎈",
    "You're like an uncharged remote—no control and no purpose. 🎮",
    "You're like a rerun of a bad TV show—nobody wants to see you again. 📺",
    "You're like a pencil without lead—totally useless. ✏️",
    "You're like a stapler with no staples—no function at all. 📎",
    "You're like a knock-knock joke with no punchline—completely pointless. 🚪",
    "You're like a sponge that doesn't absorb anything—completely useless. 🧽",
    "You're like a YouTube ad that can't be skipped—just annoying. 📢",
    "You're like a watch that doesn’t tell time—confusing and pointless. ⌚",
    "You're like a fireworks show in the rain—completely disappointing. 🎆",
    "You're like a sleeping bag with a hole—no one wants to use you. 🏕️",
    "You're like an app with one-star reviews—nobody recommends you. ⭐",
    "You're like a raincoat with holes—completely ineffective. ☔",
    "You're like a USB that doesn’t connect—completely useless. 🔌",
    "You're like a TV remote with missing buttons—frustrating to deal with. 📺",
    "You're like an alarm clock that never rings—easily ignored. ⏰",
       "You're like a cloud—when you disappear, it's a nice day. ☀️",
    "You're the reason shampoo bottles have instructions. 🧴",
    "Your secrets are safe with me. I never even listen when you tell me them. 😜",
    "You're like an expired coupon—no value at all. 🏷️",
    "You're about as useful as a car without wheels. 🚗",
    "You're like a pencil without lead—pointless. ✏️",
    "You're like an alarm clock that never rings—completely useless. ⏰",
    "Your intelligence is like a speed bump—slows everything down. 🚧",
    "You're so slow, you get outpaced by a snail on roller skates. 🐌",
    "You're like a dial-up connection in a fiber-optic world—outdated. 📶",
    "You're like a closed library—full of nothing useful. 📚",
    "You're like an elevator that only goes down—never uplifting. 🔽",
    "You're the reason aliens won't talk to us. 👽",
    "Your WiFi signal is stronger than your personality. 📡",
    "You're like a traffic jam—no one wants to be near you. 🚦",
    "You're the human version of a typo. ⌨️",
    "You're like a movie trailer for a film nobody wants to see. 🎬",
    "Your confidence is impressive for someone who is consistently wrong. ❌",
    "You're the kind of person who claps when the plane lands. 🛬",
    "You're as pointless as a square wheel. 🛞",
    "You're like a potato—round, bland, and best when silent. 🥔",
    "You're proof that not everyone should have internet access. 🌐",
    "You're like a foggy mirror—completely unclear. 🪞",
    "Your best idea was probably a mistake. 🤦",
    "You're like a printer that only prints blank pages—wasting resources. 🖨️",
    "You're like an ad that pops up when you're watching a good video. 📢",
    "You're as useful as a paper straw in boiling water. 🥤",
    "You're the human version of 'Terms and Conditions'—nobody wants to deal with you. 📄",
    "You're about as relevant as MySpace. 🖥️",
    "You're like a left turn signal on a parked car—completely unnecessary. 🚗",
    "Your comebacks are weaker than decaf coffee. ☕",
    "You're like a WiFi password at a stranger's house—completely unwanted. 🔒",
    "You're like a seatbelt on a bicycle—pointless and unnecessary. 🚴",
    "You're as inspiring as an empty notebook. 📓",
    "You're like an umbrella with holes—completely ineffective. ☔",
    "You're like a knock-knock joke with no punchline—awkward and disappointing. 🚪",
    "You're the type of person who reads the full terms and conditions and still presses accept. 📜",
    "You're like a candle in a windstorm—useless. 🕯️",
    "You're about as intimidating as a rubber duck. 🦆",
    "Your presence is like a buffering video—frustrating and unnecessary. ⏳",
    "You're like an expired milk carton—nobody wants you around. 🥛",
    "You're about as deep as a puddle. 🌊",
    "You're like a participation trophy—no one takes you seriously. 🏆",
    "You're like a pen with no ink—completely useless. 🖊️",
    "You're about as necessary as an inflatable dartboard. 🎯",
    "You're like a flashlight with dead batteries—no bright ideas. 🔦",
    "You're the reason the 'skip ad' button exists. ⏭️",
    "You're like an unplugged lamp—dim and pointless. 💡",
    "You're as helpful as a screen door on a submarine. 🚢",
    "You're the human equivalent of background noise. 🔊",
    "You're like an umbrella indoors—confusing and unnecessary. ☂️",
    "You're as memorable as last week's grocery list. 📝",
    "You're like a snowman in summer—melting away into nothing. ⛄",
    "You're as refreshing as warm soda. 🥤",
    "You're like an instruction manual for a paperclip—overcomplicated and unnecessary. 📄",
    "You're the reason why pencils have erasers. ✏️",
    "You're like an echo—repeating nonsense with no original thoughts. 🔊",
    "You're like a VHS tape in 2025—outdated and forgotten. 📼",
    "You're like a voicemail nobody listens to—completely ignored. 📞",
    "You're as unnecessary as training wheels on a motorcycle. 🏍️",
    "You're like a parachute made of rocks—completely ineffective. 🪂",
    "You're the dictionary definition of 'meh'. 😐",
    "You're like a microwave with no buttons—completely dysfunctional. 🍽️",
    "You're like a foghorn in a library—loud, annoying, and out of place. 📚",
    "You're as exciting as a beige wall. 🎨",
    "You're like a broken clock—wrong all the time. ⏰",
    "You're as useful as an ashtray on a motorcycle. 🚬",
    "You're the human version of a traffic cone—just in the way. 🚧",
    "You're like an elevator that only stops on the basement floor—always bringing things down. 🔽",
    "You're about as reliable as a weatherman in a hurricane. 🌪️",
    "You're like a social media trend—annoying and short-lived. 📲",
    "You're like a glow stick that never glows—completely pointless. 🌟",
    "You're about as useful as a single sock. 🧦",
    "You're like an off-brand charger—slow and unreliable. 🔌",
    "You're the human version of a one-star Yelp review. ⭐",
    "You're like a pen lid with no pen—completely unnecessary. 🖊️",
    "You're as sharp as a bowling ball. 🎳",
    "You're about as essential as a waterproof teabag. 🍵",
    "You're the reason people double-check their mute buttons. 🔇",
    "You're like a microwave without a door—dangerous and pointless. 🍽️",
    "You're as annoying as a YouTube ad with no skip button. 📢",
    "You're like a shadow on a cloudy day—barely noticeable. ☁️",
    "You're like a broken vending machine—always taking but never giving. 🥤",
    "You're the reason 'Ctrl + Z' exists. ⌨️",
    "You're like a Christmas tree in February—completely out of place. 🎄",
    "You're about as fun as a math test. 📏",
    "You're like an internet browser with 100 tabs open—completely overwhelmed. 🌐",
    "You're as useful as a doorbell with no button. 🚪",
    "You're the human equivalent of a low battery warning. 🔋",
    "You're like a power bank that's always dead—never helpful. 🔌",
    "You're about as necessary as a fourth wheel on a tricycle. 🚲",
    "You're like an overcooked steak—tough to deal with. 🥩",
    "You're the reason autocorrect exists. 📱",
    "You're like an umbrella that doesn’t open—no help at all. ☔",
    "You're as welcome as a mosquito at a picnic. 🦟",
]
