# Generated by Django 5.1.6 on 2025-04-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_premiumplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the plan', null=True, upload_to='subscription/images/'),
        ),
    ]
