# Generated by Django 5.1.6 on 2025-04-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_premiumplan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumplan',
            name='image',
        ),
    ]
