# Generated by Django 5.1.6 on 2025-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_premiumplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumplan',
            name='name',
            field=models.CharField(choices=[('starter', 'Starter'), ('business+', 'Business +'), ('enterprise', 'Enterprise')], max_length=50, unique=True),
        ),
    ]
