# Generated by Django 5.1.6 on 2025-04-07 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('subscription', '0010_impersonationactivitylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='impersonationactivitylog',
            old_name='metadata',
            new_name='request_data',
        ),
        migrations.RemoveField(
            model_name='impersonationactivitylog',
            name='impersonated_user',
        ),
        migrations.AddField(
            model_name='impersonationactivitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impersonationactivitylog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='impersonationactivitylog',
            name='help_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.helprequest'),
        ),
        migrations.AlterField(
            model_name='impersonationactivitylog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='impersonationactivitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='impersonationactivitylog',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='impersonationactivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
