# Generated by Django 5.1.2 on 2025-01-05 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('groups', '0005_alter_groupevent_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Personal', 'personal'), ('Availability Issues', 'availability issues'), ('Other', 'other')], max_length=100)),
                ('custom_message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_event', to='groups.groupevent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_group', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_organization', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
