# Generated by Django 5.1.2 on 2025-01-05 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('groups', '0006_absentevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_options', models.CharField(choices=[('1_day_before', '1 Day Before'), ('1_hour_before', '1 Hour Before'), ('custom', 'Custom Time')], default='1_day_before', max_length=20)),
                ('custom_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('Upcoming', 'Upcoming Event'), ('Custom', 'Custom Reminder')], default='Upcoming', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='groups.groupevent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'group', 'event', 'user', 'reminder_options', 'custom_time')},
            },
        ),
    ]
