# Generated by Django 5.1.2 on 2024-12-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='current_project',
        ),
    ]
