# Generated by Django 5.1.2 on 2024-12-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
