# Generated by Django 5.1.2 on 2024-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_holidayorganization_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayorganization',
            name='message_for_invitees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
