# Generated by Django 5.1.2 on 2024-12-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_holidayorganization_holiday_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayorganization',
            name='allow_scheduling',
        ),
        migrations.RemoveField(
            model_name='holidayorganization',
            name='holiday_visibility',
        ),
        migrations.CreateModel(
            name='HolidaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_scheduling', models.BooleanField(default=False)),
                ('holiday_visibility', models.BooleanField(default=True)),
                ('holiday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.holidayorganization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_settings', to='accounts.organization')),
            ],
        ),
    ]
