# Generated by Django 5.1.2 on 2024-12-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_holidaytype_remove_holidaysettings_is_partial_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaysettings',
            name='holiday_notifications',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
