# Generated by Django 5.1.2 on 2024-12-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_meetingorganization_meeting_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorganization',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_meetingss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingorganization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meetingss', to=settings.AUTH_USER_MODEL),
        ),
    ]
