# Generated by Django 5.1.2 on 2024-12-23 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_meetingorganization_invitee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('reminder_time', models.IntegerField(choices=[(15, '15 minutes before'), (30, '30 minutes before'), (45, '45 minutes before'), (0, 'On meeting time')], default=15)),
                ('custom_minutes', models.IntegerField(blank=True, null=True)),
                ('custom_hours', models.IntegerField(blank=True, null=True)),
                ('reminder_datetime', models.DateTimeField(blank=True, null=True)),
                ('remind_all_members', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.meetingorganization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
