# Generated by Django 5.1.2 on 2024-12-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_meetingnotes_unique_together_meetingnotes_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingnotes',
            unique_together={('organization', 'meeting')},
        ),
        migrations.RemoveField(
            model_name='meetingnotes',
            name='user',
        ),
    ]
