# Generated by Django 5.1.2 on 2025-01-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_organization_company_holidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='company_holidays',
        ),
    ]
