# Generated by Django 5.1.5 on 2025-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_organization_created_by_organization_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(blank=True, choices=[('Working Remotely', 'working_remotely'), ('In A Meeting', 'in_a_meeting'), ('Off Sick', 'off_sick'), ('On Holiday', 'on_holiday')], max_length=100, null=True),
        ),
    ]
