# Generated by Django 5.1.5 on 2025-02-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_suspend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorganization',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorganization',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorganization',
            name='meeting_location',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('zoho', 'Zoho'), ('in_person', 'In-person')], default='in_person', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorganization',
            name='meeting_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorganization',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('standup', 'Standup'), ('task', 'Task'), ('project_discussion', 'Project Discussion'), ('other', 'Other')], default='other', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorganization',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorganization',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=50, null=True),
        ),
    ]
