# Generated by Django 5.1.6 on 2025-02-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_profile_last_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_active',
            new_name='last_login',
        ),
    ]
