# Generated by Django 5.1.2 on 2024-12-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_holidayorganization_delete_ongoingmeetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayorganization',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidayorganization',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
