# Generated by Django 5.1.2 on 2024-12-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_holidayorganization_message_for_invitees'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayorganization',
            name='allow_scheduling',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
