# Generated by Django 5.1.2 on 2024-12-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_holidayorganization_allow_scheduling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaysettings',
            name='is_recurring',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
