# Generated by Django 5.1.2 on 2024-12-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_holidaysettings_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaysettings',
            name='is_partial_day',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='holidaysettings',
            name='partial_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaysettings',
            name='partial_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
