# Generated by Django 5.1.2 on 2024-12-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_holidaysettings_is_partial_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='holidaysettings',
            name='is_partial_day',
        ),
        migrations.RemoveField(
            model_name='holidaysettings',
            name='partial_end_time',
        ),
        migrations.RemoveField(
            model_name='holidaysettings',
            name='partial_start_time',
        ),
        migrations.AddField(
            model_name='holidaysettings',
            name='holiday_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.holidaytype'),
        ),
    ]
