# Generated by Django 5.1.2 on 2024-12-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_holidaysettings_notify_employees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaysettings',
            old_name='notify_employees',
            new_name='notify_organization_members',
        ),
    ]
