# Generated by Django 5.1.2 on 2024-12-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_notify_employees_holidaysettings_notify_organization_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaysettings',
            name='carryover',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
