# Generated by Django 5.1.2 on 2024-12-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_meetingorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorganization',
            name='meeting_date',
            field=models.DateField(),
        ),
    ]
