# Generated by Django 5.1.2 on 2024-12-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_meetingreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingreminder',
            name='reminder_style',
            field=models.CharField(blank=True, choices=[('minimalist', 'Minimalist'), ('modern_blue', 'Modern Blue'), ('dark_mode', 'Dark Mode'), ('elegant_pastel', 'Elegant Pastel'), ('professional_gold', 'Professional Gold')], default='minimalist', help_text='Choose a theme for your reminder email template.', max_length=100, null=True),
        ),
    ]
