# Generated by Django 5.1.2 on 2024-12-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_meetingreminder_reminder_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreminder',
            name='reminder_style',
            field=models.CharField(blank=True, choices=[('minimalist', 'Minimalist'), ('modern', 'Modern'), ('dark', 'Dark'), ('classic', 'Classic'), ('playful', 'Playful')], default='minimalist', help_text='Choose a theme for your reminder email template.', max_length=100, null=True),
        ),
    ]
