# Generated by Django 5.1.2 on 2024-12-23 13:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_meetingorganization_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvitationorganization',
            name='invite_token',
            field=models.CharField(default=accounts.models.generate_random_string, max_length=50, unique=True),
        ),
    ]
