# Generated by Django 5.1.2 on 2024-12-24 05:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agenda_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
