# Generated by Django 5.1.2 on 2024-12-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_meetingroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingnotes',
            unique_together={('organization', 'meeting')},
        ),
        migrations.RemoveField(
            model_name='meetingnotes',
            name='user',
        ),
    ]
