# Generated by Django 5.1.2 on 2024-12-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_meetingnotes_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='highlighted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
