# Generated by Django 5.1.2 on 2024-12-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_meetingnotes_highlighted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='emojis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
