# Generated by Django 5.1.2 on 2024-12-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_meetingnotes_emojis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingnotes',
            name='emojis',
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='meeting_notes/voice_messages/'),
        ),
    ]
