# Generated by Django 5.1.2 on 2024-12-25 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_meetingnotes_voice_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingnotes',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='meetingnotes',
            name='highlighted_text',
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='mentions',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentioned_in_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
