# Generated by Django 5.1.2 on 2025-01-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_eventorganization_bookingorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_holidays',
            field=models.JSONField(blank=True, null=True, verbose_name=dict),
        ),
    ]
