# Generated by Django 5.1.2 on 2025-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0006_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('COMMENT', 'Commented on the task'), ('NOTE', 'Added a note'), ('START_TIMER', 'Started the timer'), ('STOP_TIMER', 'Stopped the timer'), ('PROGRESS_UPDATE', 'Updated progress'), ('TASK_CREATED', 'Created a task'), ('TASK_COMPLETED', 'Marked task as completed'), ('TASK_PENDING', 'Marked task as pending')], max_length=50),
        ),
    ]
