# Generated by Django 5.1.2 on 2025-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tasks', '0007_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktag',
            name='name',
            field=models.CharField(choices=[('Important', 'Important'), ('Urgent', 'Urgent'), ('Low Priority', 'Low Priority'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tasktag',
            unique_together={('task', 'name')},
        ),
    ]
