# Generated by Django 5.1.2 on 2025-01-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('group_tasks', '0010_tasktimetracking'),
        ('groups', '0008_groupevent_recurrence_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('COMMENT', 'Commented on the task'), ('NOTE', 'Added a note'), ('START_TIMER', 'Started the timer'), ('STOP_TIMER', 'Stopped the timer'), ('PROGRESS_UPDATE', 'Updated progress'), ('TASK_CREATED', 'Created a task'), ('TASK_COMPLETED', 'Marked task as completed'), ('TASK_PENDING', 'Marked task as pending'), ('TAG_ADDED', 'Added a tag in task'), ('TAG_REMOVED', 'Removed the tag from task'), ('TIME_SPENT', 'Spent time on task')], max_length=50),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='accounts.organization')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_problems', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='group_tasks.task')),
                ('task_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('task', 'reported_by', 'description')},
            },
        ),
    ]
