# Generated by Django 5.1.6 on 2025-02-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_rename_messagee_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
