# Generated by Django 5.1.6 on 2025-02-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_message_code_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='custom_repeat_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='repeat',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('none', 'None'), ('custom', 'Custom')], default='none', max_length=55, null=True),
        ),
    ]
