# Generated by Django 5.1.6 on 2025-02-14 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_meetingorganization_end_time_and_more'),
        ('conversation', '0005_message_custom_repeat_datetime_message_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
