# Generated by Django 5.1.6 on 2025-02-14 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_meetingorganization_end_time_and_more'),
        ('conversation', '0006_conversation_organization_message_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user1', 'user2', 'organization')},
        ),
    ]
