# Generated by Django 5.1.6 on 2025-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder',
            field=models.CharField(blank=True, choices=[('Before 10 minutes', 'Before 10 minutes'), ('Before 20 minutes', 'Before 20 minutes'), ('Before an hour', 'Before an hour'), ('None', 'None')], default='Before 10 minutes', max_length=100, null=True),
        ),
    ]
