# Generated by Django 5.1.6 on 2025-03-07 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=100)),
                ('time', models.TimeField(help_text='Time of the meeting')),
                ('recurrence', models.CharField(choices=[('daily', 'Every Day'), ('weekly', 'Every Week'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Every Month'), ('monday', 'Every Monday'), ('tuesday', 'Every Tuesday'), ('wednesday', 'Every Wednesday'), ('thursday', 'Every Thursday'), ('friday', 'Every Friday'), ('custom', 'Custom Date')], default='weekly', help_text='Defines how often this meeting should be scheduled', max_length=20)),
                ('custom_date', models.DateField(blank=True, help_text="Only required if 'Custom Date' is selected.", null=True)),
                ('skip_if_busy', models.BooleanField(default=False, help_text='If checked, meeting will be skipped if participants are busy.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('conflict_detected', models.BooleanField(default=False, help_text='System will set this to True if scheduling conflicts are found.')),
                ('last_attempted_schedule', models.DateTimeField(blank=True, help_text='Timestamp of the last scheduling attempt.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auto_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_schedules', to='accounts.organization')),
                ('scheduled_with', models.ManyToManyField(related_name='auto_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='gui_apps_au_organiz_c4fd2b_idx'), models.Index(fields=['creator'], name='gui_apps_au_creator_9e8f51_idx'), models.Index(fields=['status'], name='gui_apps_au_status_75778c_idx')],
            },
        ),
    ]
