# Generated by Django 5.1.6 on 2025-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoschedule',
            name='remind_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
