# Generated by Django 5.1.6 on 2025-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui_apps', '0002_autoschedule_remind_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoschedule',
            name='remind_check',
            field=models.BooleanField(default=False, help_text='If checked, we will remind both creator and scheduler before meeting.'),
        ),
    ]
