# Generated by Django 5.1.6 on 2025-03-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui_apps', '0003_alter_autoschedule_remind_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoschedule',
            name='retry_if_failed',
            field=models.BooleanField(default=False, help_text='If checked,CalendarPlus will retry the meeting to schedule if failed!.'),
        ),
    ]
