# Generated by Django 5.1.5 on 2025-02-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0051_alter_project_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_from', models.DateTimeField()),
                ('hidden_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='accounts.organization')),
                ('hider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_organizations', to=settings.AUTH_USER_MODEL)),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_from', to='accounts.organization')),
            ],
        ),
    ]
