# Generated by Django 5.1.5 on 2025-02-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationhide',
            name='notify_members',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
