# Generated by Django 5.1.5 on 2025-02-10 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_meetingorganization_end_time_and_more'),
        ('organizations', '0003_organizationhide_hide_on_sundays_and_holidays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month'), ('yearly', 'Every Year'), ('custom', 'Custom')], default='weekly', max_length=10)),
                ('custom_days', models.JSONField(blank=True, help_text='Store custom recurrence days as a list [1,3,5] for Mon,Wed,Fri', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for indefinite recurrence', null=True)),
                ('remind_before', models.IntegerField(default=15, help_text='Minutes before the meeting to send a reminder')),
                ('send_email_reminder', models.BooleanField(default=True, help_text='Should an email reminder be sent?')),
                ('send_push_notification', models.BooleanField(default=True, help_text='Should a push notification be sent?')),
                ('exclude_dates', models.JSONField(blank=True, help_text='List of dates to exclude from recurrence', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_meetings_set', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recurring_meetings', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='accounts.meetingorganization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_meetings', to='accounts.organization')),
            ],
            options={
                'unique_together': {('meeting', 'recurrence_type', 'start_date')},
            },
        ),
    ]
