# Generated by Django 5.1.5 on 2025-02-10 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_meetingorganization_end_time_and_more'),
        ('organizations', '0004_recurringmeeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringmeeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_meetings_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringmeeting',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='accounts.meetingorganization'),
        ),
        migrations.AlterField(
            model_name='recurringmeeting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_meetings', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='recurringmeeting',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month'), ('yearly', 'Every Year'), ('custom', 'Custom')], default='weekly', max_length=10, null=True),
        ),
    ]
