# Generated by Django 5.1.5 on 2025-02-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_recurringmeeting_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringmeeting',
            name='type',
            field=models.CharField(blank=True, choices=[('Recurring Meeting', 'recurring_meeting'), ('Urgent', 'urgent')], default='Urgent', max_length=100, null=True),
        ),
    ]
