# Generated by Django 5.1.5 on 2025-02-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_recurringmeeting_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recurringmeeting',
            unique_together={('recurrence_type', 'start_date')},
        ),
        migrations.RemoveField(
            model_name='recurringmeeting',
            name='meeting',
        ),
    ]
