# Generated by Django 5.1.6 on 2025-02-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('organizations', '0008_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='OrganizationProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.TextField()),
                ('protection_status', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('unlock_time', models.DateTimeField(blank=True, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
    ]
