# Generated by Django 5.1.6 on 2025-02-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('organizations', '0009_remove_help_assigned_to_organizationprotection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprotection',
            name='encrypted_password',
        ),
        migrations.AddField(
            model_name='organizationprotection',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprotection',
            name='failed_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprotection',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='organizationprotection',
            name='protection_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprotection',
            name='unlock_time',
            field=models.DateTimeField(null=True),
        ),
    ]
