# Generated by Django 5.1.6 on 2025-03-01 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('organizations', '0010_remove_organizationprotection_encrypted_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('status', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_access', to='accounts.organization')),
                ('organization_protect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationprotection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
