# Generated by Django 5.1.6 on 2025-03-01 08:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('organizations', '0011_trackaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackaccess',
            options={'ordering': ['-accessed_at']},
        ),
        migrations.RemoveField(
            model_name='trackaccess',
            name='content',
        ),
        migrations.RemoveField(
            model_name='trackaccess',
            name='status',
        ),
        migrations.AddField(
            model_name='trackaccess',
            name='access_type',
            field=models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timed Out')], default='FAILED', max_length=20),
        ),
        migrations.AddField(
            model_name='trackaccess',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackaccess',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackaccess',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trackaccess',
            name='failed_attempts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trackaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trackaccess',
            index=models.Index(fields=['accessed_at'], name='organizatio_accesse_56d7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='trackaccess',
            index=models.Index(fields=['organization'], name='organizatio_organiz_233418_idx'),
        ),
        migrations.AddIndex(
            model_name='trackaccess',
            index=models.Index(fields=['user'], name='organizatio_user_id_0b33db_idx'),
        ),
    ]
