# Generated by Django 5.1.6 on 2025-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_alter_trackaccess_options_remove_trackaccess_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprotection',
            name='protect_channels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationprotection',
            name='protect_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationprotection',
            name='protect_org_detail',
            field=models.BooleanField(default=True),
        ),
    ]
