# Generated by Django 5.1.6 on 2025-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organizationprotection_protect_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprotection',
            name='protect_calendars',
            field=models.BooleanField(default=False),
        ),
    ]
