# Generated by Django 5.1.6 on 2025-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_organizationprotection_protect_calendars'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprotection',
            name='protect_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationprotection',
            name='protect_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationprotection',
            name='protect_manage_members',
            field=models.BooleanField(default=False),
        ),
    ]
