# Generated by Django 5.1.1 on 2024-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.TextField(null=True),
        ),
    ]
