# Generated by Django 5.1.1 on 2024-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_meeting_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Standup', 'Standup')], max_length=100, null=True),
        ),
    ]
