# Generated by Django 5.1.1 on 2024-10-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_meeting_meeting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Standup', 'Standup'), ('Personal', 'Personal'), ('Team', 'Team')], max_length=100, null=True),
        ),
    ]
