# Generated by Django 5.1.2 on 2024-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_docs_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='task',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
