# Generated by Django 5.1.2 on 2025-01-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_emailorganization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailorganization',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled')], default='Delivered', max_length=50, null=True),
        ),
    ]
