# Generated by Django 5.1.2 on 2025-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_emailorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailorganization',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled')], default='Delivered', max_length=50),
        ),
    ]
