# Generated by Django 5.1.2 on 2025-01-03 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        ('contacts', '0004_alter_emailorganization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('schedule_time', models.DateTimeField()),
                ('template_style', models.CharField(choices=[('Professional', 'Professional'), ('Modern', 'Modern'), ('Attractive', 'Attractive'), ('Playful', 'Playful')], default='Professional', max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_to_receive', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['schedule_time'],
            },
        ),
    ]
