from django.contrib.auth.models import User
from .models import HolidayOrganization, Profile,Organization
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from organization_channels.models import Channel
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from django.utils.html import strip_tags
from django.db.models.signals import post_save
from django.dispatch import receiver
from conversation.models import MessageSuggestion






# Predefined list of government holidays (adjust according to your country)
GOVERNMENT_HOLIDAYS = [
    {"name": "New Year's Day", "start_date": "2024-01-01", "end_date": "2024-01-01"},
    {"name": "Martin Luther King Jr. Day", "start_date": "2024-01-15", "end_date": "2024-01-15"},
    {"name": "Presidents' Day", "start_date": "2024-02-19", "end_date": "2024-02-19"},
    {"name": "Memorial Day", "start_date": "2024-05-27", "end_date": "2024-05-27"},
    {"name": "Independence Day", "start_date": "2024-07-04", "end_date": "2024-07-04"},
    {"name": "Labor Day", "start_date": "2024-09-02", "end_date": "2024-09-02"},
    {"name": "Columbus Day", "start_date": "2024-10-14", "end_date": "2024-10-14"},
    {"name": "Veterans Day", "start_date": "2024-11-11", "end_date": "2024-11-11"},
    {"name": "Thanksgiving Day", "start_date": "2024-11-28", "end_date": "2024-11-28"},
    {"name": "Christmas Day", "start_date": "2024-12-25", "end_date": "2024-12-25"},
]

# Now update the signal to create these holidays for the organization when a profile is created.



@receiver(post_save, sender=Profile)
def create_predefined_holidays(sender, instance, created, **kwargs):
    """
    Signal to create predefined government holidays for a user based on their profile's organization.
    Triggered when a new Profile is created.
    """
    if created:
        organization = instance.organization
        user = instance.user  # Get the user who is creating the profile

        # Create predefined government holidays for the organization if they don't exist
        for holiday in GOVERNMENT_HOLIDAYS:
            # Check if the holiday already exists for this organization
            if not HolidayOrganization.objects.filter(organization=organization, start_date=holiday['start_date'], end_date=holiday['end_date']).exists():
                # Create holiday with user responsible for the holiday
                HolidayOrganization.objects.create(
                    organization=organization,
                    user=user,  # Assign the user who created the holiday
                    name=holiday['name'],
                    start_date=holiday['start_date'],
                    end_date=holiday['end_date'],
                    description=f"Government holiday for {holiday['name']}",
                )
                print(f"Predefined holiday created: {holiday['name']} for organization {organization.name} by {user.username}")







# Create a social channel by default for every organization
@receiver(post_save, sender=Organization)
def create_social_channel_and_send_email(sender, instance, created, **kwargs):
    if created:  # Only run when a new organization is created
        try:
            # ✅ Get the admin profile
            admin_profile = Profile.objects.get(organization=instance, is_admin=True)
            admin_user = admin_profile.user  # Get the admin user

            # ✅ Create "Social" Channel
            Channel.objects.create(
                organization=instance,
                created_by=admin_user,
                name="Social",
                type="BLANK",
                visibility="PUBLIC",
            )

            # ✅ Send Email to Admin
            subject = "🎉 Your Organization Has Been Created!"
            context = {
                "admin_name": admin_user.get_full_name(),
                "admin_email": admin_user.email,
                "org_name": instance.name,
                "created_at": instance.created_at.strftime("%Y-%m-%d %H:%M:%S"),
            }
            html_message = render_to_string("channels/creation/org_created.html", context)
            plain_message = strip_tags(html_message)  # Convert HTML to plain text
            send_mail(
                subject,
                plain_message,
                settings.DEFAULT_FROM_EMAIL,
                [admin_user.email],
                html_message=html_message,
            )
        except Profile.DoesNotExist:
            # Handle the case where no admin profile is found
            print(f"Error: Admin profile not found for organization: {instance.name}")
        except Exception as e:
            # General error handling
            print(f"Error creating channel or sending email: {e}")



# CREATE PREDEFINED SUGGESTIONS FOR ORGANIZATION 

@receiver(post_save, sender=Organization)
def create_default_suggestions(sender, instance, created, **kwargs):
    if created:
        # Predefined suggestions for different categories
        greetings = [
    "Hello, how can I assist you?",
    "Hey there! How can I help today?",
    "Welcome! How can I be of assistance?",
    "Hi, what can I do for you?",
    "Good to see you! How can I help?",
    "Hello! How’s your day going?",
    "Hi! How can I make your day better?",
    "Hey! What brings you here today?",
    "Welcome! What can I do for you?",
    "Hi there! How may I assist you?",
    "Hello! What’s on your mind?",
    "Hey! Hope you're having a great day. How can I assist?",
    "Hi! Need help with something?",
    "Good to see you! What can I do for you today?",
    "Welcome! Let me know how I can help.",
    "Hi! How’s your day been so far?",
    "Hello there! How may I be of service?",
    "Hey! Ready to get started?",
    "Good day! How can I assist you?",
    "Hello! How’s everything going?",
    "Hi! What would you like to do today?",
    "Hey there! Need any help?",
    "Welcome back! What can I do for you?",
    "Hi! Tell me how I can assist.",
    "Hello! Let’s get things started. How can I help?",
    "Hey! What are you working on today?",
    "Good to have you here! How can I help?",
    "Hi! What brings you here today?",
    "Hello there! Need any guidance?",
    "Hey! How can I support you today?",
    "Good morning! How may I assist?",
    "Good afternoon! How can I help you?",
    "Good evening! Need any assistance?",
    "Hi! How can I make your experience better?",
    "Hey there! Anything I can do for you?",
    "Hello! Looking for something?",
    "Hi! What do you need help with?",
    "Hey there! What’s up?",
    "Hello! How can I make your day easier?",
    "Hi! How may I be of service today?",
    "Welcome! How can I add value today?",
    "Hey! What can I do for you this time?",
    "Good to see you again! How can I help?",
    "Hi there! What’s new with you?",
    "Hello! Got any questions for me?",
    "Hey! Need help navigating something?",
    "Hi! How can I make things better for you?",
    "Welcome back! Let’s get started.",
    "Hello! How can I assist on your journey today?",
    "Hey! I’m here to help—just ask.",
    "Hi! Ready to dive into something?",
    "Welcome! What’s the plan for today?",
    "Hey there! Hope you’re doing great. How can I assist?",
    "Hi! What challenge are we tackling today?",
    "Good to see you! Let’s get started.",
    "Hello! What’s on your mind today?",
    "Hey! How can I make things easier for you?",
    "Hi! Need a helping hand?",
    "Welcome! How can I be useful to you?",
    "Hello! Looking for assistance with something?",
    "Hi! What can I guide you through today?",
    "Hey there! What would you like to know?",
    "Welcome! I’m here to help however I can.",
    "Hello! What are we working on today?",
    "Hi! Need any quick assistance?",
    "Hey! Let me know how I can be of service.",
    "Welcome! What do you have in mind today?",
    "Hi! Ready to solve some problems?",
    "Hello! What’s on the agenda for today?",
    "Hey there! What’s your goal for today?",
    "Welcome! I’m here whenever you need help.",
    "Hi! How can I simplify things for you?",
    "Hello! Hope you’re having a great day. Need help?",
    "Hey! I’m all ears—what’s up?",
    "Welcome! What can I take care of for you?",
    "Hi! What’s your focus for today?",
    "Hello! Need a second opinion on something?",
    "Hey! How can I help push things forward?",
    "Good to see you! Let’s work on something great today.",
    "Hi! What are you hoping to accomplish?",
    "Welcome! Tell me what’s on your mind.",
    "Hello! Looking for help with something specific?",
    "Hey there! Let’s get to work. How can I assist?",
    "Hi! What’s the first thing on our to-do list?",
    "Welcome back! Let’s get things moving.",
    "Hello! I’m here to make things easier for you.",
    "Hey! Let’s get started. What’s first?",
    "Hi! How can I make today smoother for you?",
    "Hello there! Need some quick guidance?",
    "Hey! Let’s work through it together.",
    "Welcome! I’m happy to help. What’s up?",
    "Hi! How can I improve your experience today?",
    "Hello! What’s the most important thing today?",
    "Hey! Let’s make some progress. How can I assist?",
    "Hi! Anything I can take off your plate?",
    "Welcome! Need assistance with something right away?",
    "Hello! What’s the most pressing thing today?",
    "Hey! I’m here to help however you need.",
    "Hi! Let’s make this a productive session.",
    "Hello! What’s the next step for today?",
    "Hey! Let me know what you need help with.",
    "Welcome! How can I remove roadblocks for you?",
    "Hi! Anything that needs my attention first?",
    "Hello! Let’s tackle today’s challenges together.",
    "Hey! Got any quick questions for me?",
    "Hi! How’s your project coming along?",
    "Welcome! Need help getting unstuck?",
    "Hello! What’s a priority for you today?",
    "Hey! I’m here whenever you’re ready to start.",
    "Hi! How can I provide the best support?",
    "Welcome! What’s the top goal for today?",
    "Hello! Ready to jump into something?",
    "Hey! I’m excited to assist—what’s the task?",
    "Hi! Looking for some quick guidance?",
    "Hello! Let’s get started—how can I help?",
    "Hey there! What’s your top priority right now?",
    "Hi! What’s the biggest thing on your mind?",
    "Welcome! I’m eager to assist—what’s first?",
    "Hello! I’m here to provide solutions—what do you need?",
    "Hey! Need help prioritizing your tasks?",
    "Hi! What’s the first thing you’d like to tackle?",
    "Welcome! Let me know what I can do for you today.",
    "Hello! What do you need to accomplish right now?",
    "Hey there! What’s the next big step for you?",
    "Hi! I’m excited to assist—what’s the challenge?",
    "Welcome! I’m all set to help—just say the word.",
    "Hello! How can I help move things forward today?",
    "Hey! What’s the number one thing on your plate?",
    "Hi! I’m ready when you are—what’s first?",
    "Welcome! Let’s make some progress together.",
    "Hello! What would make today successful for you?",
    "Hey! I’m here for whatever you need.",
    "Hi! What’s the best way I can help you today?",
    "Welcome! Let’s make things happen!",
]

        
        support_messages = [
    "How can I help you today?",
    "Can I provide you with any assistance?",
    "Is there anything I can do to support you?",
    "Feel free to ask anything, I'm here to help.",
    "What do you need help with?",
    "How can I assist you right now?",
    "Is there something specific you need support with?",
    "Let me know how I can make things easier for you.",
    "I’m here to assist—what do you need help with?",
    "Feel free to ask, I'm ready to help!",
    "What can I do to help you today?",
    "Do you need help with anything?",
    "Is there any issue I can resolve for you?",
    "Let me know if you need any guidance!",
    "How can I make your experience smoother?",
    "Would you like help with anything in particular?",
    "I'm available if you need assistance!",
    "Tell me what you need, and I’ll do my best to assist.",
    "Do you require any special assistance today?",
    "Let me know if you’re facing any issues.",
    "I’d be happy to support you—what do you need?",
    "Is there anything urgent you need help with?",
    "How can I be of service to you?",
    "I’m here to support you in any way possible.",
    "Tell me how I can help!",
    "Can I guide you through something?",
    "Do you need assistance with a specific issue?",
    "I'm just a message away if you need help.",
    "Let me know if there’s anything I can do for you.",
    "If you need support, I’m right here!",
    "Is there a challenge I can help you with?",
    "How can I best support you today?",
    "Do you need me to walk you through anything?",
    "I’m here to assist—just let me know what you need!",
    "How can I help make things easier for you?",
    "Would you like any guidance on something?",
    "Let me know if something’s unclear—I’d love to help!",
    "I'm always here if you need help with anything.",
    "How can I provide the best support for you?",
    "Is there something you need help figuring out?",
    "Would you like me to provide more information on something?",
    "Do you need help troubleshooting an issue?",
    "Let me know how I can assist you today.",
    "I’d be happy to answer any questions you have.",
    "Is there anything you’re struggling with?",
    "Let me help you with whatever you need!",
    "I'm here to provide assistance whenever you need it.",
    "Do you need help making a decision?",
    "Would you like help understanding something better?",
    "If you have any concerns, I'm here to listen!",
    "I can guide you through any issue—just let me know!",
    "Would you like me to clarify something for you?",
    "I'm here to assist, no matter what the issue is!",
    "I’d love to help—just tell me what you need!",
    "Let me know if you need a solution to anything!",
    "If you’re feeling stuck, I’m happy to guide you.",
    "Would you like my advice on something?",
    "Do you need step-by-step instructions?",
    "I’d be happy to walk you through the process.",
    "Let me know what I can do to help you right now.",
    "Do you need help finding information on something?",
    "I’m ready to assist whenever you are!",
    "Would you like recommendations or suggestions?",
    "Tell me what’s on your mind, and I’ll try to help!",
    "If you need assistance, just ask!",
    "I’m happy to provide support however I can.",
    "Would you like a detailed explanation of something?",
    "Do you need guidance on the next steps?",
    "Is there something I can simplify for you?",
    "I'm here to help in any way I can!",
    "Let me know if you need help resolving an issue.",
    "Is there anything technical I can assist with?",
    "Would you like help organizing your thoughts?",
    "Do you need advice on what to do next?",
    "Tell me how I can be helpful today!",
    "Let me know if you need a different perspective on something.",
    "I’m happy to offer suggestions if needed!",
    "Would you like help planning something?",
    "If you need clarity, I’d love to help!",
    "Do you need guidance on making a choice?",
    "Would you like more information on this topic?",
    "How can I support you with this?",
    "I can assist with anything—just ask!",
    "Tell me if you need anything at all!",
    "Do you need someone to brainstorm solutions with?",
    "Would you like a fresh perspective on this?",
    "Let me know if you need help with any decisions.",
    "I’d love to assist in any way possible!",
    "If you're uncertain, I can help you figure it out!",
    "Would you like me to research something for you?",
    "Let me know if I can make something clearer.",
    "Do you need assistance troubleshooting an issue?",
    "Would you like step-by-step instructions?",
    "How can I help make things easier for you?",
    "Is there a challenge you’re facing that I can help with?",
    "Let me know how I can be the most helpful to you!",
    "I'm here to provide any support you need!",
    "Would you like me to walk you through something?",
    "Can I help you understand something better?",
    "Do you need help with any setup or configurations?",
    "Would you like recommendations tailored to your needs?",
    "Let me know what you need help with!",
    "I'm happy to assist however I can!",
    "Do you need help getting started with something?",
    "Let me know if there’s anything specific I can do for you.",
    "Would you like help breaking down a complex task?",
    "I’m here to guide you through any difficulties.",
    "If you’re unsure, I can help you figure things out!",
    "I can walk you through this if you'd like!",
    "Would you like assistance with troubleshooting?",
    "I’d love to help however I can—just ask!",
    "How can I provide better support for you?",
    "Let me know if there’s anything I can take care of for you.",
    "Would you like step-by-step guidance?",
    "Is there something you'd like me to explain in more detail?",
    "I’m happy to assist in solving any issue!",
    "Would you like some expert advice?",
    "If you need direction, I'm happy to guide you!",
    "Would you like me to handle something for you?",
    "I can help simplify any process—just ask!",
    "Do you need help making a final decision?",
    "Is there something specific you need clarification on?",
    "Would you like alternative solutions to your problem?",
    "Let me know how I can make things more efficient for you!",
    "If you’re feeling overwhelmed, I can help break it down.",
    "Do you need me to verify something for you?",
    "Would you like to go over this again?",
    "Let me know if you need more detailed assistance!",
    "If you need any follow-up support, I’m here!",
    "Would you like help prioritizing your tasks?",
    "Do you need me to summarize something for you?",
    "If you have any doubts, I can clear them up for you!",
    "Would you like me to review your options?",
    "Let me know if you need additional resources!",
    "Do you need help making sense of the information?",
    "Would you like a walkthrough of this process?",
    "I’m here to make things easier for you!",
    "Let me know how I can be most helpful to you today.",
    "I can provide examples or demonstrations if needed!",
    "Would you like me to test something for you?",
    "Do you need assistance resolving a technical issue?",
    "Is there a particular area where you need extra help?",
    "Let me know if I can assist in any way!",
]

        
        follow_up_messages = [
    "Just checking in, how are you doing?",
    "Is there anything else you'd like to ask?",
    "Do you need further assistance?",
    "Let me know if you have more questions!",
    "Would you like to know anything else?",
    "Is there something I can help you with?",
    "Feel free to ask if you have more inquiries!",
    "Can I assist you with anything else?",
    "Do you need help with something else?",
    "If you have more questions, don’t hesitate to ask.",
    "Would you like me to explain anything further?",
    "Let me know if you'd like additional support.",
    "I’m happy to help, feel free to ask more questions!",
    "Are you satisfied with the information provided?",
    "Is there anything unclear that I can help clarify?",
    "Anything else on your mind that I can assist with?",
    "Don’t hesitate to ask if you have any more doubts.",
    "How else can I assist you today?",
    "Let me know if you need further explanation!",
    "I’m here if you need anything more!",
    "Feel free to ask anything else, I'm happy to assist.",
    "Do you need help with something else, or is everything clear?",
    "Would you like more information on this topic?",
    "Anything else I can help with today?",
    "Is there another question I can answer for you?",
    "Let me know if you want more details on anything.",
    "If you need further assistance, just let me know!",
    "Would you like me to guide you through anything else?",
    "Is there something specific you’d like to explore further?",
    "Can I provide more information on something else?",
    "If you need help with anything, feel free to ask!",
    "Is there anything I missed that you’d like to know?",
    "Are you looking for something else? I’m here to assist.",
    "Let me know if you'd like to continue or have more queries.",
    "I’m available if you need more support!",
    "Feel free to let me know if you have additional questions.",
    "Do you want to learn more about this or any other topic?",
    "If you have other questions, I’ll be happy to help.",
    "Anything else I can explain or help with?",
    "Let me know if there’s anything more I can assist you with.",
    "Do you need help with any other topic?",
    "If you have any concerns, I’m happy to help!",
    "Would you like me to check something else for you?",
    "Let me know if you need any clarification.",
    "I can assist with anything else you’d like to know.",
    "Feel free to ask if you want to explore something more!",
    "Is there anything else you would like to discuss?",
    "Anything more I can assist you with today?",
    "If there’s more you need help with, I’m here for you!",
    "Let me know if you have any other questions or doubts!",
    "Feel free to reach out with any additional questions.",
    "Is there any additional information you’d like to receive?",
    "Would you like help with anything else at the moment?",
    "Can I provide further insights on this topic?",
    "Do you need more help with your current task?",
    "If you need more support, just let me know!",
    "Would you like me to guide you through more steps?",
    "Would you like to know how to proceed with this?",
    "Let me know if you want further details on any aspect.",
    "I’m happy to assist with anything else you may need.",
    "Feel free to ask me any more questions, I’m happy to help.",
    "Do you need more assistance with something?",
    "If you'd like, I can suggest more tips or details.",
    "Can I provide any other help on this matter?",
    "Is there anything I can help you improve on?",
    "Let me know if you need more help or advice!",
    "Would you like me to walk you through the next steps?",
    "If you have other questions, don’t hesitate to ask!",
    "Is there something else I can do for you?",
    "Would you like me to suggest something else?",
    "If you need any more help, I’m just a message away.",
    "Would you like further guidance on this matter?",
    "Let me know if you need any additional help!",
    "If you want to explore more, just ask!",
    "Is there something else on your mind?",
    "Would you like me to assist you with a different topic?",
    "Do you need more advice or resources?",
    "Feel free to ask for further assistance anytime.",
    "I’m always here to help if you need anything else.",
    "Let me know if you need more assistance or advice.",
    "If you want more information, I’m happy to provide it.",
    "Feel free to ask if you’re interested in something else!",
    "Would you like me to help with something else?",
    "Can I assist with another question or concern?",
    "Let me know if there’s anything else I can help with.",
    "If you’re ready for more assistance, just reach out!",
    "Is there another question you need assistance with?",
    "Would you like to continue discussing this topic?",
    "Feel free to ask for additional details, I’m here to help.",
    "Is there something else you need help with?",
    "Let me know if I can provide more assistance!",
    "Would you like to proceed with anything else?",
    "Let me know if you want further details or help.",
    "Feel free to ask me more questions anytime.",
    "Would you like me to help you find more solutions?",
    "If you want to go over anything again, just let me know.",
    "Let me know if you have any more concerns.",
    "If you need assistance with something else, I’m here.",
    "Would you like to explore more options?",
    "Feel free to ask if you need clarification or assistance.",
    "Let me know if you need help with something else!",
    "Would you like me to give you more suggestions?",
    "Can I help with anything else today?",
    "Feel free to reach out if you need additional help.",
    "Do you need any more assistance with this?",
    "Would you like me to guide you further on this?",
    "Let me know if you'd like more help with something.",
    "Is there anything you’d like to dive deeper into?",
    "Would you like to go over anything again?",
    "Let me know if there’s anything I can explain further.",
    "Feel free to reach out with any other questions!",
    "Would you like to continue discussing?",
    "Can I assist you with any other information?",
    "Do you want to ask about anything else?",
    "Feel free to reach out for more support anytime!",
    "Is there anything more you'd like to know?",
    "I’m here to help if you need more guidance.",
    "Would you like help with anything else?",
    "Let me know if you'd like me to explain anything in more detail.",
    "Would you like to proceed with a different topic?",
    "Let me know if you need anything else, I’m happy to assist!",
    "I can provide more insights if needed, just ask!",
    "Feel free to ask any more questions that come to mind.",
    "Would you like more assistance or details?",
    "Is there anything else I can assist you with right now?",
    "Let me know if you want more help with your next step.",
    "Feel free to ask anything, I’m here to assist.",
    "Would you like me to assist with any other questions?",
    "Can I help you with something else today?",
    "Feel free to ask about anything more you need.",
    "Is there anything more I can do for you?",
    "Would you like additional help on this topic?",
    "Let me know if there’s more I can assist you with.",
    "If you’d like more help, I’m here!",
    "Do you need help with any other aspect?",
    "Let me know if you have any further questions.",
    "Would you like to explore more topics?",
    "If you'd like to continue chatting, feel free to ask.",
    "Would you like me to help you with anything else?",
    "Let me know if I can help you with something else.",
    "I’m here to assist with anything you need, just ask!",
    "Let me know if you want to go over anything more."
]

        goodbye_messages = [
    "Goodbye! Let me know if you need anything in the future.",
    "Thanks for chatting! Take care!",
    "Goodbye, have a great day ahead!",
    "See you soon! Feel free to reach out if needed.",
    "Take care, talk soon!",
    "Wishing you all the best! Goodbye!",
    "Farewell, and take care of yourself!",
    "It was a pleasure chatting with you! See you soon!",
    "Thanks for your time! Have a wonderful day!",
    "Goodbye! Don’t hesitate to get in touch again.",
    "Stay safe, and take care! See you next time.",
    "Take care! I'm always here if you need help.",
    "It was great talking to you! Bye for now.",
    "Goodbye, my friend! Have a fantastic day!",
    "Until next time, stay well and take care.",
    "Goodbye for now, feel free to reach out again anytime.",
    "See you around! Wishing you all the best.",
    "Thanks for the great chat! Take care!",
    "Take care and see you soon!",
    "Goodbye! Let me know if you have more questions later.",
    "Have a wonderful day ahead! Goodbye!",
    "It was a pleasure assisting you! Stay well.",
    "Feel free to contact us if you need help. Goodbye!",
    "Take care and be safe out there!",
    "Goodbye for now! Always happy to help!",
    "Goodbye, have a peaceful day ahead.",
    "See you later, my friend! Take care!",
    "Thanks for your time! Come back anytime!",
    "Goodbye! Stay happy and healthy!",
    "Have a great rest of the day! Bye for now!",
    "Take care, and don’t hesitate to ask if you need more help.",
    "Goodbye! Stay safe, and we’re here whenever you need us.",
    "Wishing you the best of luck! Goodbye!",
    "It’s been a pleasure! Feel free to reach out again.",
    "See you next time! Take care of yourself.",
    "Goodbye, my friend! Wishing you happiness.",
    "Until we meet again, stay safe and take care!",
    "Goodbye! Thanks for the conversation.",
    "Take care and remember we’re just a message away.",
    "Goodbye, I’m always here to help when needed.",
    "Wishing you a wonderful day ahead! Goodbye!",
    "Take care! Looking forward to chatting again soon.",
    "Goodbye! May your day be filled with happiness.",
    "See you soon! Feel free to message anytime.",
    "Goodbye, stay safe and healthy!",
    "Take care! It’s always a pleasure to chat with you.",
    "Thanks for chatting! Don’t forget to reach out if you need help.",
    "Goodbye, and may your day be as wonderful as you are!",
    "Take care! Always happy to assist you.",
    "Goodbye, my friend! Wishing you all the best.",
    "It was great talking to you! Stay well.",
    "Until next time, have a fantastic day!",
    "Goodbye! See you next time, and stay safe.",
    "Take care of yourself! See you soon.",
    "Goodbye for now! Let me know if you need anything else.",
    "Thanks for your time! See you later.",
    "Goodbye! Have a wonderful time ahead.",
    "It’s been a pleasure talking to you. Take care!",
    "See you soon! Don’t hesitate to message if needed.",
    "Goodbye! Have an amazing day!",
    "Take care, my friend! Talk soon.",
    "Goodbye! I’m always here to help you out.",
    "Wishing you the best! Take care.",
    "Goodbye, see you next time!",
    "Thanks for your time! Take care and be safe.",
    "Goodbye! I’ll be here whenever you need assistance.",
    "Take care, and don’t hesitate to get back to me.",
    "See you later! Wishing you all the best.",
    "Goodbye! Thanks for your valuable time today.",
    "Take care, and may your day be peaceful.",
    "Goodbye, have a great time ahead!",
    "See you soon, stay happy!",
    "Take care of yourself and see you later.",
    "Goodbye! Reach out if you need anything more.",
    "Thanks for chatting, have a beautiful day ahead!",
    "Goodbye! Wishing you success in everything.",
    "Take care! See you soon!",
    "Goodbye, have a fantastic journey ahead.",
    "Stay safe! Goodbye for now.",
    "Goodbye! I’m here whenever you need help again.",
    "Take care, and don’t hesitate to get in touch!",
    "Goodbye! Always happy to help you!",
    "See you later! Have a wonderful time ahead.",
    "Goodbye, wishing you peace and happiness!",
    "Take care, looking forward to our next chat!",
    "Goodbye, my friend! Keep smiling!",
    "Thanks for chatting, and see you again soon!",
    "Take care! I’m always here when you need me.",
    "Goodbye! You’re always welcome to chat with us.",
    "Wishing you a great day ahead! Goodbye!",
    "Take care, and feel free to message anytime!",
    "Goodbye! Be safe, and stay happy!",
    "Goodbye, wishing you the best in everything you do.",
    "Take care! I look forward to our next conversation.",
    "Goodbye, and remember I’m just a message away!",
    "Thanks for your time! Stay safe!",
    "Goodbye, I’m always here to help you.",
    "Take care of yourself and enjoy the day ahead!",
    "Goodbye, wishing you lots of happiness!",
    "See you soon! Don’t hesitate to message.",
    "Goodbye! May your day be filled with joy.",
    "Take care, and have a great day ahead!",
    "Goodbye for now! Be well, and stay safe.",
    "Goodbye! I’m just a message away if you need anything.",
    "Take care! It was great talking with you!",
    "Goodbye, and feel free to reach out anytime.",
    "Goodbye, have a peaceful day ahead!",
    "Take care, and enjoy the rest of your day.",
    "Goodbye! Stay well and take care.",
    "Goodbye! I hope to hear from you again soon.",
    "Thanks for your time! Take care, my friend.",
    "Goodbye, wishing you all the best for today and beyond.",
    "Goodbye! Always here if you need me.",
    "Take care and see you next time!",
    "Goodbye! It was a pleasure helping you.",
    "Wishing you a great time ahead! Goodbye!",
    "Goodbye, my friend! Hope you have a wonderful time ahead.",
    "Take care and have a lovely day!",
    "Goodbye, and feel free to ask if you need anything else.",
    "Take care, and I’ll be here whenever you need help!",
    "Goodbye for now! Take care of yourself.",
    "Goodbye! Stay safe and have a wonderful time.",
    "Take care and remember, you can always reach out to us.",
    "Goodbye, hope you have a lovely rest of your day!",
    "Thanks for the chat! Have a great day ahead.",
    "Goodbye! Wishing you success in everything.",
    "Take care, and see you soon!",
    "Goodbye, and keep smiling, my friend!",
    "Goodbye! Stay healthy and take care.",
    "Take care, my friend! Wishing you happiness.",
    "Goodbye! Stay safe, and see you again soon.",
    "Goodbye! Have an amazing day ahead!",
    "Take care of yourself! Reach out if you need anything.",
    "Goodbye, I hope to see you soon!",
    "Take care! Stay awesome.",
    "Goodbye! You’re amazing, keep shining!",
    "Thanks for chatting with me! Goodbye.",
    "Take care, and don’t hesitate to contact me again!",
    "Goodbye! Always happy to chat with you.",
    "Goodbye! Keep up the great work!",
    "Take care! I look forward to our next conversation.",
    "Goodbye! Wishing you happiness and success.",
    "Goodbye, have a peaceful and happy day ahead.",
    "Take care, and may your day be filled with joy.",
    "Goodbye! Be well and take care.",
    "Goodbye for now, have a wonderful time ahead!",
    "Thanks for chatting! Take care!",
    "Goodbye! I’m here if you need anything more.",
    "Take care and enjoy the rest of your day.",
    "Goodbye! See you soon!",
]


        faq_messages = [
    "How can I reset my password?",
    "Where can I find more information on this?",
    "What is your refund policy?",
    "How can I change my account settings?",
    "Do you offer live support?",
    "How do I create an account?",
    "What payment methods do you accept?",
    "How do I update my billing information?",
    "Can I change my email address?",
    "What should I do if I forget my username?",
    "How do I deactivate my account?",
    "How long does it take to process a refund?",
    "Do you offer a free trial?",
    "Can I upgrade my plan at any time?",
    "How do I cancel my subscription?",
    "Where can I find my purchase history?",
    "Is my data secure with you?",
    "Do you offer bulk discounts?",
    "Can I get a demo of your service?",
    "How do I contact customer support?",
    "What browsers do you support?",
    "Is there a mobile app available?",
    "How do I report a bug or issue?",
    "Do you offer student discounts?",
    "What are the system requirements?",
    "Can I integrate this with other apps?",
    "Do you have a user guide or tutorials?",
    "How do I submit feedback or suggestions?",
    "Is there a limit to the number of users on my account?",
    "Can I recover a deleted account?",
    "Do you have an affiliate program?",
    "How do I change my profile picture?",
    "Are there any hidden fees?",
    "What happens when my trial ends?",
    "How often do you update the platform?",
    "Is customer support available 24/7?",
    "How do I report inappropriate content?",
    "Can I use this on multiple devices?",
    "How do I enable two-factor authentication?",
    "Do you have a community forum?",
    "Can I customize my dashboard?",
    "What languages do you support?",
    "Can I export my data?",
    "Do you offer enterprise solutions?",
    "What happens if I exceed my plan’s limits?",
    "How do I reset my security questions?",
    "Can I transfer ownership of my account?",
    "How do I set up notifications?",
    "What should I do if I don’t receive a verification email?",
    "Can I use this software offline?",
    "How do I access my invoices?",
    "Can I set different permissions for team members?",
    "Do you have a money-back guarantee?",
    "How do I verify my account?",
    "What happens if I miss a payment?",
    "Do you offer API access?",
    "How do I check my subscription status?",
    "How can I update my password?",
    "Can I use a VPN while using this service?",
    "How do I retrieve lost files or messages?",
    "What happens to my data if I cancel my account?",
    "Do you have a dark mode option?",
    "Can I schedule messages or posts?",
    "How do I change the default settings?",
    "Can I recover an accidentally deleted file?",
    "Are there any limits on file uploads?",
    "How do I request a feature?",
    "What are the benefits of upgrading my plan?",
    "Can I pause my subscription?",
    "Do you support third-party logins?",
    "How can I improve security on my account?",
    "How do I block or report a user?",
    "Can I download my usage reports?",
    "How do I import data from another service?",
    "Do you support multiple languages?",
    "Can I create multiple accounts?",
    "How do I switch between accounts?",
    "How do I turn off email notifications?",
    "Can I personalize my experience?",
    "What kind of support do you offer?",
    "Can I use this for my business?",
    "How do I check server status?",
    "Do you offer premium support?",
    "Can I set up automated workflows?",
    "How do I get notified about updates?",
    "How do I change my phone number?",
    "Can I share my account with someone else?",
    "Are there video tutorials available?",
    "How do I find the best plan for me?",
    "Can I request an invoice before purchase?",
    "How do I update my profile details?",
    "Do you support integrations with other platforms?",
    "How do I enable or disable specific features?",
    "Can I restrict access to certain users?",
    "What’s the best way to contact support?",
    "Is my data backed up automatically?",
    "How do I change my email preferences?",
    "Can I use this software without an internet connection?",
    "Do you provide training for teams?",
    "How do I download my account data?",
    "Can I set up multi-factor authentication?",
    "How do I know if my payment was successful?",
    "Can I extend my trial period?",
    "How do I retrieve archived messages?",
    "Do you have a mobile-friendly version?",
    "How do I share files securely?",
    "What should I do if my account gets locked?",
    "Do you have regional pricing?",
    "How do I add or remove a team member?",
    "Can I schedule automatic backups?",
    "How do I check the uptime of your service?",
    "What happens if I go over my plan’s limits?",
    "How do I request priority support?",
    "Do you offer white-label solutions?",
    "How do I find tutorials on using your service?",
    "What are the most common troubleshooting steps?",
    "Can I get an extended trial for testing?",
    "What’s the difference between free and paid plans?",
    "How do I cancel my free trial?",
    "Can I transfer my subscription to another user?",
    "How do I test a feature before buying?",
    "Can I combine multiple accounts?",
    "Do you provide personalized onboarding?",
    "How do I escalate an issue with support?",
    "Can I automate repetitive tasks?",
    "What happens if I delete my account permanently?",
    "How do I migrate from a competitor?",
    "Can I save my settings for future use?",
    "Do you offer localization options?",
    "What should I do if I experience technical issues?",
    "Can I export my chat history?",
    "How do I prevent unauthorized access?",
    "Is there a way to provide feedback directly to developers?",
    "Can I set up different roles within my team?",
    "What happens if my credit card expires?",
    "How do I manage notifications across devices?",
    "Do you offer real-time collaboration features?",
    "Can I archive old data instead of deleting it?",
    "Is there a guide for new users?",
    "How do I keep track of my team’s usage?",
    "Can I turn off in-app sound notifications?",
    "What happens if I exceed my file storage limit?",
    "How do I access customer support live chat?",
    "Can I get a discount for annual billing?",
    "How do I recover my chat history?",
    "What happens if I change my subscription mid-cycle?",
    "Do you offer discounts for nonprofits?",
    "Can I use two accounts at the same time?",
    "How do I stay updated with new features?",
    "Do you provide compliance documentation?",
    "How do I remove old devices from my account?",
    "What are your data retention policies?",
    "Can I set up auto-replies?",
]

        
        # Add suggestions for the new organization
        all_suggestions = greetings + support_messages + follow_up_messages + goodbye_messages + faq_messages
        
        for suggestion_text in all_suggestions:
            MessageSuggestion.objects.create(organization=instance, content=suggestion_text)

        print(f"Default suggestions created for organization {instance.name}")


