# Generated by Django 5.1.4 on 2025-01-17 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0044_remove_organization_company_holidays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BLANK', 'Blank Channel'), ('PROJECT_STARTER', 'Project Starter Kit'), ('HELP_REQUESTS', 'Help Requests Process'), ('TEAM_SUPPORT', 'Team Support'), ('FEEDBACK', 'Feedback Intake and Triage'), ('ONBOARDING', 'New Hire Onboarding'), ('COACHING', '1:1 Coaching'), ('SALES_TRACKING', 'Sales Deal Tracking')], default='BLANK', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public - Anyone in Organization'), ('PRIVATE', 'Private - Specific People Only')], default='PUBLIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_members', models.ManyToManyField(blank=True, related_name='allowed_channels', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='accounts.organization')),
            ],
        ),
    ]
