# Generated by Django 5.1.4 on 2025-01-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='allowed_members',
        ),
    ]
