# Generated by Django 5.1.2 on 2024-12-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_plus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
