# Generated by Django 5.1.6 on 2025-04-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('calendar', 'Calendar'), ('tasks', "Today's Tasks"), ('meetings', 'Upcoming Meetings'), ('notes', 'Notes'), ('leaderboard', 'Leaderboard'), ('calculation', 'Calculation')], max_length=50),
        ),
    ]
