# Generated by Django 5.1.6 on 2025-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboardwidget_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('calendar', 'Calendar'), ('tasks', "Today's Tasks"), ('meetings', 'Upcoming Meetings'), ('notes', 'Notes'), ('leaderboard', 'Leaderboard'), ('calculation', 'Calculation'), ('workload', 'Workload'), ('progress', 'Progress'), ('overdue_tasks', 'Overdue tasks'), ('due_soon', 'Due soon'), ('bookmarks', 'Bookmarks')], max_length=50),
        ),
    ]
