# Generated by Django 5.1.6 on 2025-04-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks_widget', '0002_recentactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentactivity',
            name='organization',
        ),
    ]
