# Generated by Django 5.1.6 on 2025-04-12 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks_widget', '0003_remove_recentactivity_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Recent Activity', 'verbose_name_plural': 'Recent Activities'},
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('read', 'Read'), ('other', 'Other')], default='other', help_text='Type of action performed.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Optional human-readable context.', null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Optional JSON context for flexibility.', null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='model_name',
            field=models.CharField(blank=True, help_text='Name of the model affected (optional).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='object_id',
            field=models.CharField(blank=True, help_text='ID of the object affected (optional).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='method',
            field=models.CharField(blank=True, help_text='HTTP method used.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='path',
            field=models.CharField(blank=True, help_text='Full path accessed (with or without query string).', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitiess', to=settings.AUTH_USER_MODEL),
        ),
    ]
