# Generated by Django 5.1.2 on 2024-11-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='available_dates',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='buffer_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='meeting_duration',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='availability',
            name='slots',
            field=models.JSONField(default=list),
        ),
    ]
