# Generated by Django 5.1.2 on 2024-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_remove_availability_available_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='slots',
        ),
        migrations.AddField(
            model_name='availability',
            name='buffer_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='meeting_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_recurring',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
