# Generated by Django 5.1.2 on 2024-11-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_remove_availability_slots_availability_buffer_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='buffer_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='meeting_duration',
        ),
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
