# Generated by Django 5.1.2 on 2024-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_remove_availability_buffer_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='created_at',
        ),
        migrations.AddField(
            model_name='availability',
            name='buffer_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='meeting_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
