# Generated by Django 5.1.2 on 2024-11-28 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_remove_availability_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('meeting_duration', models.PositiveIntegerField(blank=True, help_text='Duration of the meeting in minutes', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.organization')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meets_organized', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='meets_participated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
