# Generated by Django 5.1.2 on 2024-11-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_meets_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meets',
            name='participant',
        ),
    ]
