# Generated by Django 5.1.2 on 2024-11-30 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0016_meets_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meets',
            name='participant',
        ),
        migrations.AddField(
            model_name='meets',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='participant_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
