# Generated by Django 5.1.2 on 2024-11-30 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0018_remove_meets_participant_meets_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meets',
            name='participants',
        ),
        migrations.AddField(
            model_name='meets',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
