# Generated by Django 5.1.2 on 2024-11-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0019_remove_meets_participants_meets_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meets',
            name='participants',
        ),
    ]
