# Generated by Django 5.1.2 on 2024-11-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0022_meets_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
