# Generated by Django 5.1.2 on 2024-12-01 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0026_meetinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meets',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='meets',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='meetings_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
