# Generated by Django 5.1.6 on 2025-03-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='mini_apps/icons/')),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('communication', 'Communication'), ('task_management', 'Task Management'), ('entertainment', 'Entertainment'), ('utility', 'Utility'), ('other', 'Other')], default='other', max_length=50)),
                ('developer', models.CharField(default='Unknown Developer', max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('size', models.CharField(default='0.0MB', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('install_count', models.PositiveIntegerField(default=0)),
                ('commands', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
