# Generated by Django 5.1.6 on 2025-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0002_miniapp_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniapp',
            name='related_images',
            field=models.ImageField(blank=True, null=True, upload_to='mini_apps/images/'),
        ),
    ]
