# Generated by Django 5.1.6 on 2025-03-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0003_miniapp_related_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniapp',
            name='related_images',
        ),
        migrations.CreateModel(
            name='MiniAppImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mini_apps/images/')),
                ('mini_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='app_marketplace.miniapp')),
            ],
        ),
    ]
