# Generated by Django 5.1.6 on 2025-03-03 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0004_remove_miniapp_related_images_miniappimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniappimage',
            name='mini_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_imagess', to='app_marketplace.miniapp'),
        ),
    ]
