# Generated by Django 5.1.6 on 2025-03-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0005_alter_miniappimage_mini_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniapp',
            name='ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
