# Generated by Django 5.1.6 on 2025-03-03 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_organization_created_by'),
        ('app_marketplace', '0006_miniapp_ratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledMiniApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('mini_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='app_marketplace.miniapp')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mini_app', 'organization')},
            },
        ),
    ]
