# Generated by Django 5.1.6 on 2025-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0008_taskmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniapp',
            name='docs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
