# Generated by Django 5.1.6 on 2025-03-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0012_fileupload_shared_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='shared_by',
        ),
    ]
