# Generated by Django 5.1.6 on 2025-03-06 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0013_remove_fileupload_shared_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='unique_link',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='downloaded_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='downloaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
