# Generated by Django 5.1.6 on 2025-03-06 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0014_remove_fileupload_unique_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='unique_link',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
